[package]
name = "beet_core_macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description = "Macros for beet_core"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true


[lib]
proc-macro = true

[dependencies]
beet_utils = { workspace = true, features = ["tokens"] }
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
proc-macro2-diagnostics.workspace = true

[dev-dependencies]
sweet.workspace = true
