

clear:
	rm -rf .cache || true

inspect:
	cargo build
	sweet watch --cmd "npx @modelcontextprotocol/inspector cargo run"



mddoc:
	RUSTDOCFLAGS="-Z unstable-options --output-format json" \
	cargo doc \
	--target-dir target/doc
	cargo run --bin mddoc