[package]
name = "todo-app"
edition = "2024"
version = "0.0.1"
publish = false

[features]
default = ["launch", "server", "client"]
launch = ["beet/launch"]
server = ["beet/server"]
server-local = ["server", "beet/native-tls"]
server-lambda = ["server", "beet/aws", "beet/lambda"]
client = ["beet/client"]


[dependencies]
serde = "1"
beet = { path = "../../" }
