//! 🥁🥁🥁 This file has been auto generated by the Beet router.
//! 🥁🥁🥁 Any changes will be overridden if the file is regenerated.
pub mod index;
pub const INDEX: &'static str = "/docs";
use crate::prelude::*;
#[cfg(not(target_arch = "wasm32"))]
pub fn collect() -> RouteTree<crate::prelude::StaticRoute> {
	RouteTree {
		mod_path: std::path::PathBuf::from(file!()),
		children: vec![],
		routes: Vec::new(),
	}
	.add_route((RouteInfo::new("/docs", "get"), index::get))
}
