# This is the config file for both the beet site
# and a test site used for internal testing.
#
# It contains some custom parts to handle the internal nature
# of the beet site, an external starter project will be significantly simpler.

[codegen_native]
package_name = "beet_site"
output = "crates/beet_site/src/codegen/mod.rs"
docs_route = "/docs"
wasm_imports = ["use beet::design as beet_design;", "use beet::prelude::*;"]
file_group_routes = ["beet_design_mockups"]
foo = true


[[codegen_native.file_group]]
package_name = "beet_router"
name = "test_site_pages"
path = "crates/beet_router/src/test_site/pages"
output = "crates/beet_router/src/test_site/codegen/pages.rs"
include = ["*.rs"]
exclude = ["*mod.rs"]
import_tokens = ["use crate::as_beet::*;"]


# example of how to perform codegen for a workspace crate
[[codegen_native.file_group]]
name = "beet_design_mockups"
# preset = "mockup"
package_name = "beet_design"
path = "crates/beet_design/src"
output = "crates/beet_design/src/codegen/mockups.rs"
include = ["*.mockup.*"]
base_route = "/design"
replace_route = [{ from = ".mockup", to = "" }]
import_tokens = ["#[allow(unused_imports)]use crate::prelude::*;"]


# [wasm]
# import_tokens = ["use beet::design as beet_design;", "use beet::prelude::*;"]
