# This is the beet.toml for the beet_site and codegen testing
# for a starter beet.toml see crates/beet_new_web/beet.toml
[route_codegen]
package_name = "beet_site"
output = "crates/beet_site/src/codegen/mod.rs"


[workspace.filter]
include = [
	"*/crates/beet_design/src/**/*",
	"*/crates/beet_site/src/**/*",
	"*/crates/beet_router/src/test_site/**/*",
]
exclude = ["*/target/*", "*/.cache/*", "*/node_modules/*"]


[[route_codegen.collection]]
name = "pages"
package_name = "beet_site"
path = "crates/beet_site/src/pages"
output = "crates/beet_site/src/codegen/pages/mod.rs"
import_tokens = [
	"#[allow(unused_imports)]use beet::prelude::*;",
	"#[allow(unused_imports)]use crate::prelude::*;",
]

[[route_codegen.collection]]
name = "docs"
package_name = "beet_site"
path = "crates/beet_site/src/docs"
output = "crates/beet_site/src/codegen/docs/mod.rs"
base_route = "/docs"
meta_type = "ArticleMeta"
import_tokens = [
	"#[allow(unused_imports)]use beet::prelude::*;",
	"#[allow(unused_imports)]use crate::prelude::*;",
]

[[route_codegen.collection]]
name = "blog"
package_name = "beet_site"
path = "crates/beet_site/src/blog"
output = "crates/beet_site/src/codegen/blog/mod.rs"
base_route = "/blog"
meta_type = "ArticleMeta"
import_tokens = [
	"#[allow(unused_imports)]use beet::prelude::*;",
	"#[allow(unused_imports)]use crate::prelude::*;",
]


[[route_codegen.collection]]
name = "actions"
package_name = "beet_site"
path = "crates/beet_site/src/actions"
output = "crates/beet_site/src/codegen/actions/mod.rs"
base_route = "/actions"
category = "Actions"
import_tokens = [
	"#[allow(unused_imports)]use beet::prelude::*;",
	"#[allow(unused_imports)]use crate::prelude::*;",
]

# example of how to perform codegen for a workspace crate
[[route_codegen.collection]]
name = "beet_design_mockups"
# preset = "mockup"
package_name = "beet_design"
path = "crates/beet_design/src"
meta_type = "ArticleMeta"
output = "crates/beet_design/src/codegen/mockups.rs"
include = ["*.mockup.*"]
exclude = ["*/codegen/*"]
base_route = "/design"
replace_route = [{ from = ".mockup", to = "" }]
import_tokens = ["#[allow(unused_imports)]use crate::prelude::*;"]

# [[route_codegen.collection]]
# package_name = "beet_router"
# name = "test_site_pages"
# path = "crates/beet_router/src/test_site/pages"
# output = "crates/beet_router/src/test_site/codegen/pages.rs"
# include = ["*.rs"]
# exclude = ["*mod.rs"]
# import_tokens = ["use crate::as_beet::*;"]


[client_island_codegen]
package_name = "beet_site"
output = "crates/beet_site/src/codegen/client_islands.rs"
import_tokens = [
	"#[allow(unused_imports)]use beet::design as beet_design;",
	"#[allow(unused_imports)]use beet::prelude::*;",
]
