[package]
name = "beet_template"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true


[features]
default = ["nightly"]
# default = ["nightly", "bevy_default"]
nightly = []
bevy_default = ["bevy/bevy_text"]
tokens = ["beet_common/tokens"]

[dependencies]
beet_template_macros.workspace = true
beet_common.workspace = true
sweet = { workspace = true, features = ["bevy"] }

#💡 utils
anyhow.workspace = true
thiserror.workspace = true
extend.workspace = true
strum.workspace = true
rapidhash.workspace = true
strum_macros.workspace = true
prettyplease.workspace = true
http.workspace = true

# temp until proper bevy reactivity
flume.workspace = true

#💡 html
html-escape = { version = "0.2", optional = true }

#💡 serde
serde = { workspace = true, optional = true }
ron = { workspace = true, optional = true }

#💡 bevy
bevy = { workspace = true }

#💡 native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sweet = { workspace = true, features = ["fs"] }
tokio.workspace = true

#💡 wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
sweet = { workspace = true, features = ["web"] }
console_log.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true


[dev-dependencies]
beet_template = { path = "", features = ["tokens"] }
sweet = { workspace = true, features = ["test", "bevy"] }
