use crate::prelude::*;
use beet_core::prelude::*;

/// An additional signature the entity's canonical [`Action`] serves.
///
/// It holds a full `Action<In, Out>` adapting that canonical action to a
/// different signature, eg a typed route handler adapted to
/// `Request -> Response`. Being no [`Action`] itself it never collides with the
/// canonical one and never touches the canonical fields of [`ActionMeta`]; it
/// registers its pair in the meta's overloads instead, which is what
/// [`ActionMeta::serves`] and call resolution read.
///
/// An overload delegates to its entity's canonical action directly, never back
/// through resolution, so an overload whose pair coincides with the canonical
/// one can never recurse: resolution prefers the canonical action, so such an
/// overload is simply never invoked.
///
/// Not [`Reflect`]: like the action it adapts, it is regenerated by its owner's
/// `#[require]` on scene reload.
#[derive(Component)]
#[component(
	on_add = ActionOverload::<In, Out>::on_add,
	on_remove = ActionOverload::<In, Out>::on_remove
)]
pub struct ActionOverload<In: 'static, Out: 'static>(Action<In, Out>);

impl<In: 'static, Out: 'static> Clone for ActionOverload<In, Out> {
	fn clone(&self) -> Self { Self(self.0.clone()) }
}

impl<In: 'static, Out: 'static> From<Action<In, Out>>
	for ActionOverload<In, Out>
{
	fn from(action: Action<In, Out>) -> Self { Self(action) }
}

impl<In: 'static, Out: 'static> ActionOverload<In, Out> {
	/// Wrap an adapting action as an overload of its entity's canonical action.
	pub fn new(action: Action<In, Out>) -> Self { Self(action) }

	/// The adapting action, invoked when no canonical `Action<In, Out>` matches.
	pub fn action(&self) -> &Action<In, Out> { &self.0 }

	/// Register this pair in the entity's [`ActionMeta`], creating an
	/// [`unset`](ActionMeta::unset) one if the canonical [`Action`] has not landed
	/// yet. Deferred through [`Commands`], as is [`Action`]'s own meta insert, and
	/// order-independent: whichever runs second merges into the first's meta.
	fn on_add(mut world: DeferredWorld, cx: HookContext) {
		let entity = cx.entity;
		world.commands().queue(move |world: &mut World| {
			let Ok(mut entity_mut) = world.get_entity_mut(entity) else {
				return;
			};
			let mut meta = entity_mut
				.get::<ActionMeta>()
				.cloned()
				.unwrap_or_else(ActionMeta::unset);
			meta.insert_overload::<In, Out>();
			// insert rather than edit in place, so `Insert<ActionMeta>` consumers
			// see the registered pair
			entity_mut.insert(meta);
		});
	}

	/// Deregister this pair, so the meta never advertises a signature the entity
	/// no longer serves.
	fn on_remove(mut world: DeferredWorld, cx: HookContext) {
		if let Some(mut meta) = world.get_mut::<ActionMeta>(cx.entity) {
			meta.remove_overload::<In, Out>();
		}
	}
}

#[cfg(test)]
mod test {
	use crate::prelude::*;
	use beet_core::prelude::*;

	fn double() -> Action<i32, i32> {
		Action::new_pure(|cx: ActionContext<i32>| (*cx * 2).xok())
	}
	/// Adapts the canonical `i32 -> i32` action to a `String -> String` call.
	fn stringify() -> ActionOverload<String, String> {
		ActionOverload::new(Action::new_async(
			async |cx: ActionContext<String>| -> Result<String> {
				let input = cx.input.parse::<i32>()?;
				let action = cx
					.caller
					.get(|action: &Action<i32, i32>| action.clone())
					.await?;
				cx.caller
					.call_detached(action, input)
					.await
					.map(|out| out.to_string())
			},
		))
	}

	#[beet_core::test]
	async fn serves_when_no_canonical_match() {
		AsyncPlugin::world()
			.spawn((double(), stringify()))
			.call::<String, String>("21".into())
			.await
			.unwrap()
			.xpect_eq("42".to_string());
	}

	#[beet_core::test]
	fn registers_and_deregisters_its_pair() {
		let mut world = World::new();
		let entity = world.spawn((double(), stringify())).id();
		world.flush();
		let meta = world.get::<ActionMeta>(entity).unwrap();
		meta.serves::<String, String>().xpect_true();
		meta.serves::<i32, i32>().xpect_true();

		world
			.entity_mut(entity)
			.remove::<ActionOverload<String, String>>();
		world.flush();
		world
			.get::<ActionMeta>(entity)
			.unwrap()
			.serves::<String, String>()
			.xpect_false();
	}

	/// The overload registers before the canonical action's own meta insert when
	/// the hooks run in that order, so the canonical fields must merge into the
	/// meta the overload created rather than clobber it.
	#[beet_core::test]
	fn registration_is_order_independent() {
		let mut world = World::new();
		let entity = world.spawn((stringify(), double())).id();
		world.flush();
		let meta = world.get::<ActionMeta>(entity).unwrap();
		meta.serves::<String, String>().xpect_true();
		meta.serves::<i32, i32>().xpect_true();
	}
}
