target := '--target x86_64-unknown-linux-gnu'
backtrace := ''
features := ''
rust_log := 'RUST_LOG=info'
# backtrace := 'RUST_BACKTRACE=0'

test *args:
	{{rust_log}} {{backtrace}} cargo run --example test_beet_net {{target}} {{features}} -- {{args}}
test-w *args:
	{{rust_log}} {{backtrace}} just watch 'cargo run --example test_beet_net {{target}} {{features}} -- -w {{args}}'


watch *args:
	forky watch \
	-w '**/*.rs' \
	-i '{.git,target}/**/*' \
	-i '**/mod.rs' \
	-i '**/*_g.rs' \
	-- {{args}}


