use crate::prelude::*;
use beet_core::prelude::*;

/// Metadata about an action, usually used for analysis and model calls,
/// but not required for general action usage and rendering.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionMeta {
	/// The ID of the action this metadata is associated with.
	pub action_id: ActionId,
	/// The provider this action was generated by.
	pub provider_slug: String,
	pub model_slug: String,
	/// Generated either by the model provider or the client.
	pub response_id: String,
	/// Used by model providers to distinguish between different items.
	pub item_id: String,
	/// Used by model providers to distinguish between different item parts.
	pub content_index: Option<u32>,
	/// Required for FunctionCall and FunctionCallOutput actions.
	pub call_id: Option<String>,
}

impl Document for ActionMeta {
	type Id = ActionId;
	fn id(&self) -> Self::Id { self.action_id }
}
impl ActionMeta {
	pub fn action_id(&self) -> ActionId { self.action_id }
	pub fn call_id(&self) -> Option<&str> { self.call_id.as_deref() }
}
