use crate::prelude::*;
use beet_core::prelude::*;
use serde::Deserialize;
use serde::Serialize;

pub type ActorId = DocId<Actor>;

#[derive(
	Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize,
)]
pub struct Actor {
	id: ActorId,
	/// The name of the actor used when building context
	name: String,
	kind: ActorKind,
}

impl Document for Actor {
	fn id(&self) -> DocId<Self> { self.id }
}

impl Actor {
	pub fn new(name: impl AsRef<str>, kind: ActorKind) -> Self {
		Self {
			id: default(),
			name: name.as_ref().to_string(),
			kind,
		}
	}
	pub fn system() -> Self { Self::new("System", ActorKind::System) }
	pub fn developer() -> Self { Self::new("Developer", ActorKind::Developer) }
	pub fn user() -> Self { Self::new("User", ActorKind::Human) }
	pub fn clanker() -> Self { Self::new("Clanker", ActorKind::Agent) }

	pub fn name(&self) -> &str { &self.name }
	pub fn kind(&self) -> ActorKind { self.kind }
}

/// The kind of actor this entity is.
/// Distinct from [`OpenResponses::MessageRole`] in that
/// [`ActorKind`] is absolute, whereas the difference between
/// `MessageRole::User` and `MessageRole::Asssistant` is relative
/// to the agent
#[derive(
	Debug,
	Clone,
	Copy,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
	/// Messages generated by this actor will always be treated as [`MessageRole::System`]
	System,
	/// Messages generated by this actor will always be treated as [`MessageRole::Developer`]
	Developer,
	/// Messages generated by this actor will always be treated as [`MessageRole::User`]
	Human,
	/// Messages generated by this actor may be treated as [`MessageRole::Assistant`] or [`MessageRole::User`],
	/// depending on the originator of the message.
	Agent,
}

/// A list of items belonging to this actor that are in progress,
/// awaiting either this process or an external model to complete some step:
/// - Text Streaming
/// - Function Calls
/// - Reasoning
#[derive(Component, Deref)]
pub struct ItemsInProgress(Vec<PartialContent>);

/// A partial content item, which may be created from various sources and
/// may be merged into a full content item if it fully resolves.
pub enum PartialContent {
	FunctionCall {
		/// The unique ID of the item
		id: String,
		/// The unique ID of the function tool call, shared
		/// by both this item and its associated [`FunctionCallOutput`]
		call_id: String,
		/// The name of the function that was called, in beet this is usually
		/// the [`std::any::TypeId`] for matching against a [`ToolMeta::handler`]
		name: String,
		/// The arguments JSON string that was generated.
		arguments: String,
	},
	/// Created by an `OutputItem::Message(Message::content)`
	Text {
		/// The unique ID of the item
		id: String,
		partial_text: String,
	},
	/// Created by an `OutputItem::Reasoning(ReasoningItem::summary)`
	ReasoningDescription {
		/// The unique ID of the item
		id: String,
		description: Vec<String>,
	},
	/// The actual reasoning
	/// Created by an `OutputItem::Reasoning(ReasoningItem::content)`,
	/// this is often not shown to users by default, but could be enabled by a setting
	ReasoningContent {
		/// The unique ID of the item
		id: String,
		content: Vec<String>,
	},
}
