use crate::prelude::*;
use beet_core::prelude::*;
use serde::Deserialize;
use serde::Serialize;
use uuid::Uuid;

#[derive(
	Debug,
	Clone,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
	Component,
)]
#[component(on_add=on_add)]
#[component(on_remove=on_remove)]
pub struct Actor {
	/// The name of the actor used when building context
	name: String,
	id: ActorId,
	kind: ActorKind,
	/// A list of items that may have been created by this
	/// actor or others, to be included in clanker context
	/// or rendered in ui.
	///
	/// ## Sorting
	/// This list is sorted by [`ItemId`] which, as a `uuid::v7`,
	/// is basically chronological within a millisecond, and
	/// not accounting for clock skew in the case of distributed
	/// creation. This is generally acceptible for the use-case of
	/// agent context.
	items: Vec<ItemId>,
}

fn on_add(mut world: DeferredWorld, cx: HookContext) {
	let actor_id = world.entity(cx.entity).get::<Actor>().unwrap().id;
	world
		.resource_mut::<ContextMap>()
		.add_actor(actor_id, cx.entity);
}
fn on_remove(mut world: DeferredWorld, cx: HookContext) {
	let actor_id = world.entity(cx.entity).get::<Actor>().unwrap().id;
	world.resource_mut::<ContextMap>().remove_actor(actor_id);
}

impl Actor {
	pub fn new(name: impl AsRef<str>, kind: ActorKind) -> Self {
		Self {
			name: name.as_ref().to_string(),
			kind,
			id: ActorId::new_now(),
			items: Vec::new(),
		}
	}
	pub fn system() -> Self { Self::new("System", ActorKind::System) }
	pub fn developer() -> Self { Self::new("Developer", ActorKind::Developer) }
	pub fn user() -> Self { Self::new("User", ActorKind::Human) }
	pub fn clanker() -> Self { Self::new("Clanker", ActorKind::Agent) }
	pub fn kind(&self) -> ActorKind { self.kind }
	pub fn id(&self) -> ActorId { self.id }

	/// Get the list of items associated with this actor, sorted by creation time.
	pub fn items(&self) -> &[ItemId] { &self.items }
	/// Add the item to the list, maintaining uniqueness and sort order.
	/// Returns `true` if the item was inserted.
	pub fn push(&mut self, item_id: ItemId) -> bool {
		if let Some(last) = self.items.last() {
			// usually already sorted
			if item_id >= *last {
				self.items.push(item_id);
				return true;
			}
		}
		match self.items.binary_search(&item_id) {
			Ok(_) => {
				// already in the list, do nothing
				false
			}
			Err(i) => {
				self.items.insert(i, item_id);
				true
			}
		}
	}
}

/// The kind of actor this entity is.
/// Distinct from [`OpenResponses::MessageRole`] in that
/// [`ActorKind`] is absolute, whereas the difference between
/// `MessageRole::User` and `MessageRole::Asssistant` is relative
/// to the agent
#[derive(
	Debug,
	Clone,
	Copy,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
	/// Messages generated by this actor will always be treated as [`MessageRole::System`]
	System,
	/// Messages generated by this actor will always be treated as [`MessageRole::Developer`]
	Developer,
	/// Messages generated by this actor will always be treated as [`MessageRole::User`]
	Human,
	/// Messages generated by this actor may be treated as [`MessageRole::Assistant`] or [`MessageRole::User`],
	/// depending on the originator of the message.
	Agent,
}



/// Id associated with an [`Actor`].
/// Actors are components and already have an associated [`Entity`],
/// but we need something more easily handled by distributed systems,
/// databases etc. See also [`ItemId`]
#[derive(
	Debug,
	Clone,
	Copy,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Deref,
	Serialize,
	Deserialize,
)]
pub struct ActorId(Uuid);

impl std::fmt::Display for ActorId {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		self.0.fmt(f)
	}
}

impl ActorId {
	fn new_now() -> Self { Self(Uuid::now_v7()) }
	pub fn uuid(&self) -> Uuid { self.0 }
}

/// A list of items belonging to this actor that are in progress,
/// awaiting either this process or an external model to complete some step:
/// - Text Streaming
/// - Function Calls
/// - Reasoning
#[derive(Component, Deref)]
pub struct ItemsInProgress(Vec<PartialContent>);

/// A partial content item, which may be created from various sources and
/// may be merged into a full content item if it fully resolves.
pub enum PartialContent {
	FunctionCall {
		/// The unique ID of the item
		id: String,
		/// The unique ID of the function tool call, shared
		/// by both this item and its associated [`FunctionCallOutput`]
		call_id: String,
		/// The name of the function that was called, in beet this is usually
		/// the [`std::any::TypeId`] for matching against a [`ToolMeta::handler`]
		name: String,
		/// The arguments JSON string that was generated.
		arguments: String,
	},
	/// Created by an `OutputItem::Message(Message::content)`
	Text {
		/// The unique ID of the item
		id: String,
		partial_text: String,
	},
	/// Created by an `OutputItem::Reasoning(ReasoningItem::summary)`
	ReasoningDescription {
		/// The unique ID of the item
		id: String,
		description: Vec<String>,
	},
	/// The actual reasoning
	/// Created by an `OutputItem::Reasoning(ReasoningItem::content)`,
	/// this is often not shown to users by default, but could be enabled by a setting
	ReasoningContent {
		/// The unique ID of the item
		id: String,
		content: Vec<String>,
	},
}
