use crate::prelude::*;
use beet_core::prelude::*;
use serde::Deserialize;
use serde::Serialize;

pub type ActorId = Uuid7<Actor>;

#[derive(
	Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize,
)]
pub struct Actor {
	id: ActorId,
	/// The name of the actor used when building context
	name: String,
	kind: ActorKind,
}

impl Document for Actor {
	type Id = ActorId;
	fn id(&self) -> Self::Id { self.id }
}

impl Actor {
	pub fn new(name: impl AsRef<str>, kind: ActorKind) -> Self {
		Self {
			id: default(),
			name: name.as_ref().to_string(),
			kind,
		}
	}
	pub fn system() -> Self { Self::new("System", ActorKind::System) }
	pub fn developer() -> Self { Self::new("Developer", ActorKind::Developer) }
	pub fn user() -> Self { Self::new("User", ActorKind::Human) }
	pub fn clanker() -> Self { Self::new("Clanker", ActorKind::Agent) }

	pub fn name(&self) -> &str { &self.name }
	pub fn kind(&self) -> ActorKind { self.kind }
}

/// The kind of actor this entity is.
/// Distinct from [`OpenResponses::MessageRole`] in that
/// [`ActorKind`] is absolute, whereas the difference between
/// `MessageRole::User` and `MessageRole::Asssistant` is relative
/// to the agent
#[derive(
	Debug,
	Clone,
	Copy,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
	/// Messages generated by this actor will always be treated as [`MessageRole::System`]
	System,
	/// Messages generated by this actor will always be treated as [`MessageRole::Developer`]
	Developer,
	/// Messages generated by this actor will always be treated as [`MessageRole::User`]
	Human,
	/// Messages generated by this actor may be treated as [`MessageRole::Assistant`] or [`MessageRole::User`],
	/// depending on the originator of the message.
	Agent,
}
