//!
//!```
//!Entity Structure
//!
//! Context
//!   Actor::human
//!   Actor::human
//!   Tools, Actor::agent
//!   Tools, Actor::agent
//!```
use beet_core::prelude::*;
use beet_net::prelude::Url;
use serde::Deserialize;
use serde::Serialize;

use crate::openresponses::MessageRole;

#[derive(Component)]
pub struct Context {
	/// An append-only list of content created by various actors.
	items: Vec<Item>,
}



pub struct Timestamp(Duration);



/// Note that MessageRole is not stored
/// as this is relative to the Actor.
pub struct Item {
	actor_id: ActorId,
	created: Timestamp,
	content: Content,
}

pub enum Content {
	Text(TextContent),
	File(FileContent),
	FunctionCall(FunctionCall),
	FunctionCallOutput(FunctionCallOutput),
}

/// Common type for several openresponses types
/// [`ContentPart::InputText`]
/// [`ContentPart::OutputText`] - annotations inlined as markdown
/// [`ContentPart::ReasoningSummary`]
///
/// Note that [`ContentPart::ReasoningText`] is discarded and not stored.
pub struct TextContent {
	content: String,
}

/// Common type for several openresponses types
/// [`ContentPart::InputImage`]
/// [`ContentPart::InputFile`]
/// [`ContentPart::InputVideo`]
pub struct FileContent {
	/// The name of the file without a path or extension.
	pub file_stem: Option<String>,
	pub media_type: MediaType,
	/// The file data.
	pub file_data: Url,
}

pub struct FunctionCall {
	/// The unique ID of the function tool call, shared
	/// by both this item and its associated [`FunctionCallOutput`]
	pub call_id: String,
	/// The name of the function that was called.
	pub name: String,
	/// The arguments JSON string that was generated.
	pub arguments: String,
}


pub struct FunctionCallOutput {
	/// The unique ID of the function tool call, shared
	/// by both this item and its associated [`FunctionCall`]
	pub call_id: String,
	/// The name of the function that was called.
	pub name: String,
	/// The arguments JSON string that was generated.
	pub arguments: String,
}

pub enum Message {}


#[derive(Component)]
pub struct Actor {
	kind: ActorKind,
	id: ActorId,
}

impl Actor {
	pub fn message_role(&self, agent_id: ActorId) -> MessageRole {
		match self.kind {
			ActorKind::System => MessageRole::System,
			ActorKind::Developer => MessageRole::Developer,
			ActorKind::Human => MessageRole::User,
			ActorKind::Agent => {
				if self.id == agent_id {
					MessageRole::Assistant
				} else {
					MessageRole::User
				}
			}
		}
	}
}

/// The kind of actor this entity is.
/// Distinct from [`OpenResponses::MessageRole`] in that
/// [`ActorKind`] is absolute, whereas the difference between
/// `MessageRole::User` and `MessageRole::Asssistant` is relative
/// to the agent
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
	/// Messages generated by this actor will always be treated as [`MessageRole::System`]
	System,
	/// Messages generated by this actor will always be treated as [`MessageRole::Developer`]
	Developer,
	/// Messages generated by this actor will always be treated as [`MessageRole::User`]
	Human,
	/// Messages generated by this actor may be treated as [`MessageRole::Assistant`] or [`MessageRole::User`],
	/// depending on the originator of the message.
	Agent,
}


#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActorId(u64);

impl ActorId {
	pub const SYSTEM: Self = Self(0);
	pub const DEVELOPER: Self = Self(1);
	pub fn new() -> Self {
		use std::sync::atomic::AtomicU64;
		use std::sync::atomic::Ordering;
		static NEXT_ID: AtomicU64 = AtomicU64::new(2);
		let id = NEXT_ID.fetch_add(1, Ordering::SeqCst);
		if id == u64::MAX {
			panic!("ActorId overflow");
		}
		Self(id)
	}
}


pub enum PartialContext {
	/// Created by an `OutputItem::Message(Message::content)`
	MessageContent(String),
	/// Created by an `OutputItem::Reasoning(ReasoningItem::summary)`
	ReasoningDescription(Vec<String>),
	/// The actual reasoning
	/// Created by an `OutputItem::Reasoning(ReasoningItem::content)`,
	/// this is often not shown to users by default, but could be enabled by a setting
	ReasoningContent(Vec<String>),
}
