use crate::prelude::*;
use beet_core::prelude::*;

/// Metadata about actions generated by agents, usually used for analysis and model calls,
/// but not required for general action usage and rendering.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResponseMeta {
	/// The ID of the action this metadata is associated with.
	pub action_id: ActionId,
	/// The provider this action was generated by.
	pub provider_slug: String,
	pub model_slug: String,
	/// Generated either by the model provider or the client.
	pub response_id: String,
	/// The provider has indicated that this response is stored,
	/// enabling previous_response_id
	pub response_stored: bool,
}

impl Document for ResponseMeta {
	type Id = ActionId;
	fn id(&self) -> Self::Id { self.action_id }
}
impl ResponseMeta {	
	pub fn action_id(&self) -> ActionId { self.action_id }
	pub fn response_id(&self) -> &str { &self.response_id }
}
