


# run example *args:
# 	# cargo build --example 
# 	just flash {{example}}

build example *args:
	cargo build --example {{example}} {{args}}

monitor:
	cargo espflash monitor --port=/dev/ttyACM0

run example:
	cargo espflash flash \
	--baud 921600 \
	--monitor \
	--port=/dev/ttyACM0 \
	--example {{example}}