


# run example *args:
# 	# cargo build --example 
# 	just flash {{example}}

PORT := '/dev/ttyACM0'

build example *args:
	cargo build --example {{example}} {{args}}

monitor:
	cargo espflash monitor --port={{PORT}}

run example *args:
	cargo espflash flash \
	--baud 921600 \
	--flash-size 16mb \
	--partition-table partitions.csv \
	--port={{PORT}} \
	--example {{example}} \
	--monitor \
	--release \
	{{args}}

clean:
	cargo clean && rm -rf .embuild && cargo b