//! Token usage statistics for the OpenResponses API.

use serde::Deserialize;
use serde::Serialize;

/// Token usage statistics recorded for a response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Usage {
	/// The number of input tokens used to generate the response.
	pub input_tokens: u32,
	/// The number of output tokens generated by the model.
	pub output_tokens: u32,
	/// The total number of tokens used.
	pub total_tokens: u32,
	/// A breakdown of input token usage.
	#[serde(default)]
	pub input_tokens_details: Option<InputTokensDetails>,
	/// A breakdown of output token usage.
	#[serde(default)]
	pub output_tokens_details: Option<OutputTokensDetails>,
}

impl Usage {
	/// Creates a new Usage instance.
	pub fn new(input_tokens: u32, output_tokens: u32) -> Self {
		Self {
			input_tokens,
			output_tokens,
			total_tokens: input_tokens + output_tokens,
			input_tokens_details: None,
			output_tokens_details: None,
		}
	}
}

/// A breakdown of input token usage.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InputTokensDetails {
	/// The number of input tokens that were served from cache.
	pub cached_tokens: u32,
}

/// A breakdown of output token usage.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutputTokensDetails {
	/// The number of output tokens attributed to reasoning.
	pub reasoning_tokens: u32,
}


#[cfg(test)]
mod test {
	use super::*;

	#[test]
	fn deserializes_usage() {
		let json = r#"{
			"input_tokens": 15,
			"output_tokens": 7,
			"total_tokens": 22,
			"input_tokens_details": {"cached_tokens": 0},
			"output_tokens_details": {"reasoning_tokens": 0}
		}"#;

		let usage: Usage = serde_json::from_str(json).unwrap();
		assert_eq!(usage.input_tokens, 15);
		assert_eq!(usage.output_tokens, 7);
		assert_eq!(usage.total_tokens, 22);
		assert_eq!(usage.input_tokens_details.unwrap().cached_tokens, 0);
		assert_eq!(usage.output_tokens_details.unwrap().reasoning_tokens, 0);
	}

	#[test]
	fn creates_usage() {
		let usage = Usage::new(100, 50);
		assert_eq!(usage.total_tokens, 150);
	}
}
