//! This module is for building the files typically associated with ssg apps like html & css.
//!
//! Additionally in the same pass it will collect the entrypoints for islands,
//! exporting
mod apply_route_templates;
pub use apply_route_templates::*;
mod client_island_map;
pub use client_island_map::*;
mod spa_to_html_file;
pub use spa_to_html_file::*;
mod routes_to_client_island_map;
pub use routes_to_client_island_map::*;
mod route_funcs_to_rsx;
pub use route_funcs_to_rsx::*;
mod routes_to_html;
pub use routes_to_html::*;


/// Default local paths for build artifacts produced and consumed by various build stages
pub mod default_paths {
	use sweet::prelude::*;

	/// Generated by BuildTemplateMap when statically analyzing rsx files, and extracting
	/// a map of RsxNodeTemplates.
	pub const RSX_TEMPLATES: &str = "target/rsx-templates.ron";

	/// Generated in the SSG pass
	pub const CLIENT_ISLANDS: &str = "target/client-islands.ron";

	pub fn client_islands() -> AbsPathBuf {
		WorkspacePathBuf::new(CLIENT_ISLANDS).into_abs_unchecked()
	}
}
