use crate::prelude::*;
use beet_core::prelude::*;

pub type ActorId = Uuid7<Actor>;

#[derive(
	Debug,
	Clone,
	PartialEq,
	Eq,
	Hash,
	Serialize,
	Deserialize,
	Reflect,
	Component,
)]
#[reflect(Serialize, Deserialize, Component)]
pub struct Actor {
	id: ActorId,
	/// The name of the actor used when building context
	name: String,
	kind: ActorKind,
	/// Extensible key-value metadata.
	metadata: Map,
}

impl Table for Actor {
	type Id = ActorId;
	fn id(&self) -> Self::Id { self.id }
}

impl Actor {
	pub fn new(name: impl Into<String>, kind: ActorKind) -> Self {
		Self {
			id: default(),
			name: name.into(),
			kind,
			metadata: default(),
		}
	}
	pub fn system() -> Self { Self::new("System", ActorKind::System) }
	pub fn developer() -> Self { Self::new("Developer", ActorKind::Developer) }
	pub fn user() -> Self { Self::new("User", ActorKind::User) }
	pub fn agent() -> Self { Self::new("Agent", ActorKind::Agent) }

	pub fn name(&self) -> &str { &self.name }
	pub fn kind(&self) -> ActorKind { self.kind }
	pub fn metadata(&self) -> &Map { &self.metadata }
	pub fn metadata_mut(&mut self) -> &mut Map { &mut self.metadata }
}


/// The kind of actor this entity is.
/// Distinct from [`OpenResponses::MessageRole`] in that
/// [`ActorKind`] is absolute, whereas the difference between
/// `MessageRole::User` and `MessageRole::Asssistant` is relative
/// to the agent
#[derive(
	Debug,
	Clone,
	Copy,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
	Reflect,
)]
#[reflect(Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
	/// Messages generated by this actor will always be treated as [`MessageRole::System`]
	System,
	/// Messages generated by this actor will always be treated as [`MessageRole::Developer`]
	Developer,
	/// Messages generated by this actor will always be treated as [`MessageRole::User`]
	User,
	/// Messages generated by this actor may be treated as [`MessageRole::Assistant`] or [`MessageRole::User`],
	/// depending on the originator of the message.
	Agent,
}

impl std::fmt::Display for ActorKind {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			ActorKind::System => write!(f, "system"),
			ActorKind::Developer => write!(f, "developer"),
			ActorKind::User => write!(f, "human"),
			ActorKind::Agent => write!(f, "agent"),
		}
	}
}


impl ActorKind {
	pub fn input_str(&self) -> &'static str {
		match self {
			ActorKind::System => "system",
			ActorKind::Developer => "developer",
			ActorKind::User => "human",
			ActorKind::Agent => "agent",
		}
	}
}
