use crate::prelude::*;
use beet_core::prelude::*;

/// Metadata about posts generated by agents, usually used for analysis and model calls,
/// but not required for general post usage and rendering.
#[derive(
	Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Reflect, Component,
)]
#[reflect(Serialize, Deserialize, Component)]
pub struct ResponseMeta {
	/// The ID of the post this metadata is associated with.
	pub post_id: PostId,
	/// The provider this post was generated by.
	pub provider_slug: SmolStr,
	pub model_slug: SmolStr,
	/// Generated either by the model provider or the client.
	pub response_id: SmolStr,
	/// The provider has indicated that this response is stored,
	/// enabling previous_response_id
	pub response_stored: bool,
}

impl Table for ResponseMeta {
	type Id = PostId;
	fn id(&self) -> Self::Id { self.post_id }
}
impl ResponseMeta {
	pub fn post_id(&self) -> PostId { self.post_id }
	pub fn response_id(&self) -> &str { &self.response_id }
}
