//! The variant `<select>` of a [`DynamicForm`](super::DynamicForm)'s
//! payload-carrying enum control.
//!
//! An enum value is `{"Variant": payload}` (or the bare `"Variant"` of a unit
//! one), which no single `<option>` value can express. So the control is a pair:
//! this select edits *which variant* the field carries, and the payload's own
//! generated controls edit the rest, regenerated by the
//! [`ValueRebuild`](super::ValueRebuild) the two sit in.
use crate::prelude::*;
use beet_core::prelude::*;

/// Marks the `<select>` of a payload-carrying enum control, whose own [`Value`]
/// is the variant *name* rather than the field's value.
///
/// The one generated control that does not mirror its field, because what it
/// edits is a projection of it. It still binds exactly one
/// `(document, field path)` and writes only through it, so nothing here
/// reconstructs an edit by diffing or holds a copy of a document.
#[derive(Component)]
pub(super) struct VariantSelect {
	/// The enum field this select chooses the variant of.
	pub(super) field: FieldRef,
	/// Each variant as the whole value choosing it writes: `"Name"` for a unit
	/// variant, `{"Name": zero}` for a payload-carrying one. Values, not
	/// schemas: the registry owns those, and a generation is built from the
	/// schema in place ([`ValueSchema::default_value_in`] resolved it here).
	variants: Vec<(SmolStr, Value)>,
}

/// The select for `schema`, showing the variant `current` names.
pub(super) fn variant_select(
	resolver: SchemaResolver,
	schema: &EnumSchema,
	field: &FieldRef,
	current: Option<SmolStr>,
) -> Snippet {
	let variants = schema
		.variants
		.iter()
		.map(|variant| {
			(variant.name.clone(), variant.default_value(resolver, 0))
		})
		.collect::<Vec<_>>();
	let name = field.field_path.to_string();
	let select = VariantSelect {
		field: field.clone(),
		variants,
	};
	// the local value is the variant name, seeded from what the field holds, so
	// a select rendered for a value never asks to change it
	let value = Value::Str(current.unwrap_or_default());
	rsx! {
		<Select name={name} {(select, value)}>
			{super::dynamic_form::variant_options(schema)}
		</Select>
	}
	.any_snippet()
}

/// The variant an enum value carries: a unit variant is its own bare name, a
/// payload-carrying one the single key of its externally tagged map.
pub(super) fn variant_name(value: &Value) -> Option<SmolStr> {
	match value {
		Value::Str(name) => Some(name.clone()),
		Value::Map(map) if map.len() == 1 => map.keys().next().cloned(),
		_ => None,
	}
}

/// System: a chosen variant becomes that variant's zero in the bound field.
///
/// Equality-guarded like every other sync: a select showing what the field
/// already carries is reporting, not asking, so only a *changed* variant writes.
/// Registered by [`FormPlugin`](super::FormPlugin), the plugin that owns control
/// behavior.
pub(super) fn write_selected_variant(
	selects: Populated<(Entity, &VariantSelect, &Value), Changed<Value>>,
	mut docs: DocumentQuery,
) -> Result {
	for (entity, select, value) in selects.iter() {
		let Ok(chosen) = value.as_str() else {
			continue;
		};
		let Some((_, next)) = select
			.variants
			.iter()
			.find(|(name, _)| name.as_str() == chosen)
		else {
			continue;
		};
		let current = docs
			.field_value(entity, &select.field)
			.unwrap_or_default()
			.xmap(|value| variant_name(&value));
		if current.as_deref() == Some(chosen) {
			continue;
		}
		let next = next.clone();
		docs.with_field(entity, &select.field, move |slot| *slot = next)?;
	}
	OK
}
