//! The `beet` command-line interface: a scene runner.
//!
//! Like a game engine pressing play with no scene loaded, `beet` does nothing on
//! its own. On startup it looks for a `beet.json` in the cwd: absent, it serves a
//! welcome page; present, it loads that scene (which supplies the actual CLI)
//! under the host and watches the file for live reloads. The default CLI scene is
//! generated by the `default_cli` example.
use beet::prelude::*;
use beet_cli::prelude::*;

fn main() -> AppExit {
	// load any local `.env` so eg `BEET_REMOTE_URL` is picked up by the scene
	// commands before the app starts.
	env_ext::load_dotenv();
	App::new()
		.add_plugins((
			MinimalPlugins,
			LogPlugin::default(),
			ClientAppPlugin,
			// the runner must know every command type a `beet.json` can reference, so
			// the loaded scene's markers reconstruct their behaviour: the built-in
			// build/run/export commands and the scene-control commands.
			CliCommandsPlugin,
			SceneCommandsPlugin,
			SceneManagementPlugin,
		))
		.run()
}
