//! The `beet` command-line interface: a scene controller.
//!
//! `beet` is built around scene management: its only built-in commands are
//! `load`/`clear`/`reset`/`dump`/`run`, spawned by [`start_server`] on startup.
//! It carries *retained state* — on startup it rehydrates the last scene from a
//! local `.beet/scene.json`, so a `beet load <file>` survives across invocations.
//! Other capabilities (`run-wasm`, `export-pdf`, …) ship as a loadable
//! `utils-cli` scene generated by the `export_scenes` example.
use beet::prelude::*;
use beet_cli::prelude::*;

fn main() -> AppExit {
	// load any local `.env` so eg `BEET_REMOTE_URL` is picked up by the scene
	// commands before the app starts.
	env_ext::load_dotenv();
	App::new()
		.add_plugins((
			MinimalPlugins,
			LogPlugin::default(),
			ClientAppPlugin,
			// register the loadable command types so a scene's markers can
			// reconstruct their behaviour: the `utils-cli` commands and the
			// built-in scene commands.
			CliCommandsPlugin,
			SceneManagementPlugin,
		))
		// spawn the host + built-in scene commands and rehydrate `.beet/scene.json`.
		.add_systems(Startup, start_server)
		.run()
}
