//! The `beet` command-line interface: a scene controller.
//!
//! `beet` is built around scene management: its only built-in commands are
//! `load`/`clear`/`reset`/`dump`/`run`. It carries *retained state* — on startup
//! it rehydrates the last scene from a local `.beet/scene.json`, so a
//! `beet load <file>` survives across invocations. Other capabilities
//! (`serve`, `run-wasm`, `export-pdf`, …) ship as a loadable `default-cli` scene
//! generated by the `export_scenes` bin.
//!
//! [`SceneManagementPlugin`] wires the reactive cache + watcher machinery; the
//! CLI only has to spawn its host entity, which [`spawn_host`] does on startup
//! before the plugin's `rehydrate_scene_cache` loads any retained scene under it.
use beet::prelude::*;
use beet_cli::prelude::*;

fn main() -> AppExit {
	// load any local `.env` so eg `BEET_REMOTE_URL` is picked up by the scene
	// commands before the app starts.
	env_ext::load_dotenv();
	let mut app = App::new();
	app.add_plugins((
		MinimalPlugins,
		LogPlugin::new(Level::DEBUG),
		ClientAppPlugin,
		// register the loadable command types so a scene's markers can
		// reconstruct their behaviour: the `default-cli` commands and the
		// built-in scene commands.
		CliCommandsPlugin,
		SceneManagementPlugin,
		// the style rule set `beet serve` / `beet present` sites render with
		material::MaterialStylePlugin::default(),
	));
	// the live terminal target `beet present` boots: the charcell host loop and
	// the current-page painter, the same stack `beet_site` layers under its `tui`
	// feature. `init_plugin` is idempotent, so `NavigatorPlugin` (already added by
	// `ClientAppPlugin`) is not added twice. The one-shot render path ignores these.
	#[cfg(feature = "tui")]
	app.init_plugin::<CharcellTuiPlugin>()
		.init_plugin::<NavigatorPlugin>()
		.init_plugin::<LivePagePlugin>();
	// spawn the host before the plugin rehydrates the retained scene under it.
	app.add_systems(Startup, spawn_host.before(rehydrate_scene_cache))
		.run()
}

/// Spawn the CLI host: a single [`CliServer`] + [`default_router`] carrying the
/// built-in scene commands. Scenes load *under* it as route children, mirroring
/// the device's `HttpServer` host.
///
/// The host is spawned, then triggered with [`StartServer::all`]; carrying only
/// a [`CliServer`], it runs one argv exchange and exits. A
/// `beet serve <site> --server=http` invocation's `--server` param (carried in
/// the request to the `serve` route) starts the [`HttpServer`] on the site root,
/// never hijacking this controller host.
///
/// The host claims no bespoke `/` route: an empty `beet` answers through the
/// router's not-found middleware (a route listing), and a loaded scene is free to
/// supply its own `/` root without colliding with a host-owned home route.
fn spawn_host(world: &mut World) {
	// spawn the host first (registering each server's `on_add` observers), then
	// trigger the start so the `cli` boot is never missed.
	world
		.spawn((CliServer, default_router(), children![
			SceneLoad, SceneClear, SceneReset, SceneDump, SceneRun,
		]))
		.trigger(StartServer::all);
}
