//! 🥁🥁🥁 This file has been auto generated by the Beet router.
//! 🥁🥁🥁 Any changes will be overridden if the file is regenerated.
pub mod contributing;
pub mod docs;
pub mod index;
pub const CONTRIBUTING: &'static str = "/contributing";
pub const INDEX: &'static str = "/";

use crate::prelude::*;
pub fn collect_file_routes(router: &mut crate::prelude::DefaultFileRouter) {
	router
		.add_route((RouteInfo::new("/contributing", "get"), contributing::get));
	router.add_route((RouteInfo::new("/", "get"), index::get));
	docs::collect_file_routes(router);
}
