extern crate alloc;
use alloc::string::ToString;
use alloc::vec::Vec;
use beet_core_shared::prelude::*;
use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::quote;
use syn::FnArg;
use syn::ItemFn;
use syn::ReturnType;
use syn::Type;
use syn::parse_macro_input;

pub fn impl_action(
	attr: proc_macro::TokenStream,
	item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
	parse(attr.into(), parse_macro_input!(item as ItemFn))
		.unwrap_or_else(|err| err.into_compile_error())
		.into()
}

fn parse(attr: TokenStream, item: ItemFn) -> syn::Result<TokenStream> {
	// ── 1. Parse attributes ──
	let attrs = AttributeMap::parse(attr)?;
	attrs.assert_types(&[], &["result_out", "route", "pure", "default"])?;
	let result_out = attrs.contains_key("result_out");
	let is_pure = attrs.contains_key("pure");
	let has_route = attrs.contains_key("route");
	let derive_default = attrs.contains_key("default");
	let route_expr: Option<&syn::Expr> = attrs.get("route");

	// ── 2. Extract function data ──
	let beet_action = pkg_ext::internal_or_beet("beet_action");
	let vis = &item.vis;
	let fn_name = &item.sig.ident;
	let body = &item.block;
	let generics = &item.sig.generics;
	let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
	let fn_attrs = &item.attrs;
	let is_async = item.sig.asyncness.is_some();
	let is_system = !is_async && !is_pure;
	let action_fn_name = action_fn_name(fn_name);
	let turbofish = make_turbofish(generics);

	// ── 3. Determine action kind ──
	// async → async action, pure → func action, otherwise system action
	let action_factory = if is_async {
		quote! { #beet_action::prelude::Action::new_async }
	} else if is_pure {
		quote! { #beet_action::prelude::Action::new_pure }
	} else {
		quote! { #beet_action::prelude::Action::new_system }
	};
	let async_kw = if is_async {
		quote! { async }
	} else {
		TokenStream::default()
	};

	// ── 4. Analyze parameters and build function parts ──
	let (in_type, fn_params, preamble) = if is_system {
		make_system_fn_parts(&item, &beet_action)?
	} else {
		make_simple_fn_parts(&item, &beet_action)?
	};
	let out_type = compute_out_type(&item, result_out);
	let return_type = match &item.sig.output {
		ReturnType::Default => quote! { () },
		ReturnType::Type(_, ty) => quote! { #ty },
	};

	// ── 5. Build struct definition ──
	let action_expr = quote! { #action_factory(#action_fn_name #turbofish) };
	let require_action = make_require_action(
		action_expr,
		&in_type,
		&out_type,
		has_route,
		&beet_action,
	);
	let is_middleware = has_next_type(&in_type);
	let struct_def = make_struct_def(
		vis,
		fn_name,
		generics,
		fn_attrs,
		Some(require_action),
		route_expr,
		is_middleware,
	);
	let default_impl = if derive_default {
		make_default(fn_name, generics)
	} else {
		TokenStream::default()
	};

	// ── 6. Build handler function at module level ──
	// The handler must live at module scope so that both `IntoAction`
	// and `#[require]` (generated by the Component derive) can
	// reference it.
	let handler_fn = quote! {
		#[allow(non_snake_case)]
		#async_kw fn #action_fn_name #impl_generics (#fn_params) -> #return_type #where_clause {
			#preamble
			#[allow(unused_braces)]
			#body
		}
	};

	// ── 7. Build IntoAction impl ──
	let into_action = quote! {
		impl #impl_generics #beet_action::prelude::IntoAction<#fn_name #ty_generics> for #fn_name #ty_generics #where_clause {
			type In = #in_type;
			type Out = #out_type;

			fn into_action(self) -> #beet_action::prelude::Action<Self::In, Self::Out> {
				#action_factory(#action_fn_name #turbofish)
			}
		}
	};

	// ── 8. Assemble output ──
	Ok(quote! {
		#handler_fn
		#struct_def
		#default_impl
		#into_action
	})
}


// ---------------------------------------------------------------------------
// Parameter analysis for async/func actions
// ---------------------------------------------------------------------------

/// Build function parts for async and func (pure) actions.
///
/// These actions accept at most one parameter. Returns `(in_type, fn_params, preamble)`.
fn make_simple_fn_parts(
	item: &ItemFn,
	beet_action: &syn::Path,
) -> syn::Result<(TokenStream, TokenStream, TokenStream)> {
	let params: Vec<&syn::PatType> = item
		.sig
		.inputs
		.iter()
		.map(|arg| match arg {
			FnArg::Typed(pt) => Ok(pt),
			FnArg::Receiver(recv) => {
				synbail!(
					recv,
					"`self` parameters are not supported in action functions"
				)
			}
		})
		.collect::<syn::Result<Vec<_>>>()?;

	if params.len() > 1 {
		synbail!(
			&item.sig,
			"action functions accept at most one parameter; \
			 use a tuple for multiple values: `(a, b): (A, B)`"
		);
	}

	match params.first() {
		None => {
			// No params → input is ()
			let in_type = quote! { () };
			let fn_params =
				quote! { __action_cx: #beet_action::prelude::ActionContext };
			let preamble = quote! { let _ = __action_cx.input; };
			Ok((in_type, fn_params, preamble))
		}
		Some(pt) => {
			let ty = pt.ty.as_ref();
			if let Some(inner) = extract_action_context_type(ty) {
				// Passthrough: user gets the full ActionContext
				let param_name = pat_to_ident(&pt.pat)?;
				let in_type = quote! { #inner };
				let fn_params = quote! {
					#param_name: #beet_action::prelude::ActionContext<#inner>
				};
				let preamble = TokenStream::default();
				Ok((in_type, fn_params, preamble))
			} else {
				// Bare input: destructure from context
				let pat = &pt.pat;
				let in_type = quote! { #ty };
				let fn_params = quote! {
					__action_cx: #beet_action::prelude::ActionContext<#ty>
				};
				let preamble = quote! { let #pat = __action_cx.input; };
				Ok((in_type, fn_params, preamble))
			}
		}
	}
}


// ---------------------------------------------------------------------------
// Parameter analysis for system actions
// ---------------------------------------------------------------------------

/// Build function parts for system actions.
///
/// Detects input via `In<T>` or `ActionContext<T>` on the first parameter.
/// Remaining parameters are forwarded as system params.
/// Returns `(in_type, fn_params, preamble)`.
fn make_system_fn_parts(
	item: &ItemFn,
	beet_action: &syn::Path,
) -> syn::Result<(TokenStream, TokenStream, TokenStream)> {
	for arg in &item.sig.inputs {
		if let FnArg::Receiver(recv) = arg {
			synbail!(
				recv,
				"`self` parameters are not supported in action functions"
			);
		}
	}

	let first_param = item.sig.inputs.first().and_then(|arg| match arg {
		FnArg::Typed(pt) => Some(pt),
		_ => None,
	});

	let system_params_from = |skip: usize| -> Vec<&FnArg> {
		item.sig.inputs.iter().skip(skip).collect()
	};

	let (in_type, first_fn_param, preamble, sys_params) = match first_param {
		None => {
			// No params at all
			let in_type = quote! { () };
			let first = quote! {
				In(__action_cx): In<#beet_action::prelude::ActionContext>
			};
			let preamble = quote! { let _ = __action_cx.input; };
			(in_type, first, preamble, Vec::new())
		}
		Some(pt) => {
			let ty = pt.ty.as_ref();

			if let Some(in_inner) = extract_wrapper_type(ty, "In") {
				// First param is In<...>
				if let Some(inner) = extract_action_context_type(in_inner) {
					// In<ActionContext<T>> → system passthrough
					let param_name = pat_to_ident(&pt.pat)?;
					let in_type = quote! { #inner };
					let first = quote! {
						In(#param_name): In<#beet_action::prelude::ActionContext<#inner>>
					};
					let preamble = TokenStream::default();
					(in_type, first, preamble, system_params_from(1))
				} else {
					// In<T> → system action with input T
					let param_name = pat_to_ident(&pt.pat)?;
					let in_type = quote! { #in_inner };
					let first = quote! {
						In(__action_cx): In<#beet_action::prelude::ActionContext<#in_inner>>
					};
					let preamble =
						quote! { let #param_name = In(__action_cx.input); };
					(in_type, first, preamble, system_params_from(1))
				}
			} else if let Some(inner) = extract_action_context_type(ty) {
				// ActionContext<T> without In wrapper → system passthrough
				let param_name = pat_to_ident(&pt.pat)?;
				let in_type = quote! { #inner };
				let first = quote! {
					In(#param_name): In<#beet_action::prelude::ActionContext<#inner>>
				};
				let preamble = TokenStream::default();
				(in_type, first, preamble, system_params_from(1))
			} else {
				// No input marker → all params are system params
				let in_type = quote! { () };
				let first = quote! {
					In(__action_cx): In<#beet_action::prelude::ActionContext>
				};
				let preamble = quote! { let _ = __action_cx.input; };
				(in_type, first, preamble, system_params_from(0))
			}
		}
	};

	let fn_params = if sys_params.is_empty() {
		first_fn_param
	} else {
		quote! { #first_fn_param #(, #sys_params)* }
	};

	Ok((in_type, fn_params, preamble))
}


// ---------------------------------------------------------------------------
// Type extraction helpers
// ---------------------------------------------------------------------------

/// Extract inner type, recognizing `ActionContext<T>` and its default-unit form (no generic args → `()`).
fn extract_action_context_type(ty: &Type) -> Option<Type> {
	extract_wrapper_type_or_unit(ty, "ActionContext")
}

/// Extract an identifier from a pattern.
///
/// Returns the ident for `Pat::Ident`, or a generated discard name for
/// `Pat::Wild`. Errors on complex patterns (tuples, structs, etc.).
fn pat_to_ident(pat: &syn::Pat) -> syn::Result<syn::Ident> {
	match pat {
		syn::Pat::Ident(pi) => Ok(pi.ident.clone()),
		syn::Pat::Wild(_) => Ok(syn::Ident::new(
			"__action_discard",
			proc_macro2::Span::call_site(),
		)),
		_ => synbail!(pat, "expected an identifier or `_`"),
	}
}

/// Extract the inner type `T` from a wrapper type `Wrapper<T>`, matching
/// only on the last path segment name.
fn extract_wrapper_type<'a>(ty: &'a Type, name: &str) -> Option<&'a Type> {
	if let Type::Path(type_path) = ty {
		if let Some(segment) = type_path.path.segments.last() {
			if segment.ident == name {
				if let syn::PathArguments::AngleBracketed(args) =
					&segment.arguments
				{
					if let Some(syn::GenericArgument::Type(inner)) =
						args.args.first()
					{
						return Some(inner);
					}
				}
			}
		}
	}
	None
}

/// Extract inner type for wrappers with default generic unit:
/// `Wrapper<T>` -> `T`, `Wrapper` -> `()`.
fn extract_wrapper_type_or_unit(ty: &Type, name: &str) -> Option<Type> {
	if let Some(inner) = extract_wrapper_type(ty, name) {
		Some(inner.clone())
	} else if is_wrapper_without_args(ty, name) {
		Some(syn::parse_quote! { () })
	} else {
		None
	}
}

/// Whether a type path is `Wrapper` with no generic args.
fn is_wrapper_without_args(ty: &Type, name: &str) -> bool {
	if let Type::Path(type_path) = ty {
		if let Some(segment) = type_path.path.segments.last() {
			return segment.ident == name
				&& matches!(segment.arguments, syn::PathArguments::None);
		}
	}
	false
}

/// Whether the return type path ends with `Result`.
fn is_result_type(ty: &Type) -> bool {
	if let Type::Path(type_path) = ty {
		if let Some(segment) = type_path.path.segments.last() {
			return segment.ident == "Result";
		}
	}
	false
}

/// Whether the input type contains a `Next` type, indicating middleware.
fn has_next_type(tokens: &TokenStream) -> bool {
	for tt in tokens.clone().into_iter() {
		match tt {
			proc_macro2::TokenTree::Ident(ident) if ident == "Next" => {
				return true;
			}
			proc_macro2::TokenTree::Group(group) => {
				if has_next_type(&group.stream()) {
					return true;
				}
			}
			_ => {}
		}
	}
	false
}

/// Extract the inner `T` from `Result<T>` or `Result<T, E>`.
fn extract_result_inner(ty: &Type) -> Option<&Type> {
	extract_wrapper_type(ty, "Result")
}


// ---------------------------------------------------------------------------
// Output type and body helpers
// ---------------------------------------------------------------------------

/// Compute the output type from the function signature.
fn compute_out_type(item: &ItemFn, result_out: bool) -> TokenStream {
	let raw_return_type: Option<&Type> = match &item.sig.output {
		ReturnType::Default => None,
		ReturnType::Type(_, ty) => Some(ty.as_ref()),
	};

	let returns_result = raw_return_type
		.map(|ty| is_result_type(ty))
		.unwrap_or(false);

	if let Some(ty) = raw_return_type {
		if returns_result && !result_out {
			if let Some(inner) = extract_result_inner(ty) {
				quote! { #inner }
			} else {
				quote! { () }
			}
		} else {
			quote! { #ty }
		}
	} else {
		quote! { () }
	}
}


// ---------------------------------------------------------------------------
// Struct definition and require helpers
// ---------------------------------------------------------------------------

/// Build the `#[require(...)]` expression for the `Action` component.
///
/// When `has_route` is true, requires both `Action<In, Out>` (which inserts
/// [`ActionMeta`] via its own on-add hook) and [`ExchangeAction`] for
/// type-erased request/response dispatch.
fn make_require_action(
	action_expr: TokenStream,
	in_type: &TokenStream,
	out_type: &TokenStream,
	has_route: bool,
	beet_action: &syn::Path,
) -> TokenStream {
	if has_route {
		let beet_router = pkg_ext::internal_or_beet("beet_router");
		quote! {
			#beet_action::prelude::Action<#in_type, #out_type> = #action_expr,
			#beet_router::prelude::ExchangeAction = #beet_router::prelude::ExchangeAction::new_detached::<#in_type, #out_type, _, _, _, _>(#action_expr)
		}
	} else {
		quote! {
			#beet_action::prelude::Action<#in_type, #out_type> = #action_expr
		}
	}
}

/// Generate a struct definition, forwarding function attributes to the
/// struct and optionally adding `#[require(...)]` attributes when the
/// derives include `Component`.
fn make_struct_def(
	vis: &syn::Visibility,
	fn_name: &syn::Ident,
	generics: &syn::Generics,
	fn_attrs: &[syn::Attribute],
	require_action: Option<TokenStream>,
	route_expr: Option<&syn::Expr>,
	is_middleware: bool,
) -> TokenStream {
	let has_component = has_derive(fn_attrs, "Component");
	let has_reflect = has_derive(fn_attrs, "Reflect");

	let require_action = if has_component {
		if let Some(expr) = require_action {
			quote! { #[require(#expr)] }
		} else {
			TokenStream::default()
		}
	} else {
		TokenStream::default()
	};

	let beet_action = pkg_ext::internal_or_beet("beet_action");
	let require_meta = if has_component && has_reflect && is_middleware {
		quote! {
			#[require(#beet_action::prelude::ActionMeta = #beet_action::prelude::ActionMeta::of_handler::<Self, _>())]
		}
	} else if has_component && has_reflect {
		quote! {
			#[require(#beet_action::prelude::ActionMeta = #beet_action::prelude::ActionMeta::of_reflect::<Self, _>())]
		}
	} else if has_component {
		quote! {
			#[require(#beet_action::prelude::ActionMeta = #beet_action::prelude::ActionMeta::of_action::<Self, _>())]
		}
	} else {
		TokenStream::default()
	};

	let require_path = if has_component && let Some(expr) = route_expr {
		let beet_net = pkg_ext::internal_or_beet("beet_net");
		quote! {
			#[require(#beet_net::prelude::PathPartial = #beet_net::prelude::PathPartial::new(#expr))]
		}
	} else {
		TokenStream::default()
	};

	// action structs are always unit structs or PhantomData structs,
	// both trivially cloneable
	let derive_clone = if !has_derive(fn_attrs, "Clone") {
		quote! { #[derive(Clone)] }
	} else {
		TokenStream::default()
	};

	let type_params: Vec<&syn::Ident> =
		generics.type_params().map(|tp| &tp.ident).collect();

	if type_params.is_empty() {
		quote! {
			#(#fn_attrs)*
			#derive_clone
			#require_action
			#require_meta
			#require_path
			#[allow(non_camel_case_types)]
			#vis struct #fn_name;
		}
	} else {
		let (impl_generics, _, where_clause) = generics.split_for_impl();
		let phantom = if type_params.len() == 1 {
			let tp = type_params[0];
			if has_reflect {
				quote! { fn() -> #tp }
			} else {
				quote! { #tp }
			}
		} else {
			if has_reflect {
				quote! { fn() -> (#(#type_params),*) }
			} else {
				quote! { (#(#type_params),*) }
			}
		};
		let reflect_ignore = if has_reflect {
			quote! { #[reflect(ignore)] }
		} else {
			TokenStream::default()
		};
		quote! {
			#(#fn_attrs)*
			#derive_clone
			#require_action
			#require_meta
			#require_path
			#[allow(non_camel_case_types)]
			#vis struct #fn_name #impl_generics (#reflect_ignore ::core::marker::PhantomData<#phantom>) #where_clause;
		}
	}
}

fn make_default(fn_name: &syn::Ident, generics: &syn::Generics) -> TokenStream {
	let type_params: Vec<&syn::Ident> =
		generics.type_params().map(|tp| &tp.ident).collect();
	let (impl_generics, _, where_clause) = generics.split_for_impl();

	if type_params.is_empty() {
		quote! {
			impl Default for #fn_name {
				fn default() -> Self {
					Self
				}
			}
		}
	} else {
		quote! {

			impl #impl_generics Default for #fn_name #impl_generics #where_clause {
				fn default() -> Self {
					Self(Default::default())
				}
			}
		}
	}
}


// ---------------------------------------------------------------------------
// Action-specific helpers
// ---------------------------------------------------------------------------

/// Convert a function/struct name to a snake_case standalone function
/// name with a `_action` suffix.
fn action_fn_name(fn_name: &syn::Ident) -> syn::Ident {
	let snake = fn_name.to_string().to_snake_case();
	let name = alloc::format!("{}_action", snake);
	syn::Ident::new(&name, fn_name.span())
}

/// Check whether any `#[derive(...)]` attribute contains `name`.
fn has_derive(attrs: &[syn::Attribute], name: &str) -> bool {
	attrs.iter().any(|attr| {
		if attr.path().is_ident("derive") {
			attr.parse_args_with(
				syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
			)
			.map(|meta_list| meta_list.iter().any(|path| path.is_ident(name)))
			.unwrap_or(false)
		} else {
			false
		}
	})
}

/// Generate turbofish syntax for generic type parameters,
/// or empty tokens when there are none.
fn make_turbofish(generics: &syn::Generics) -> TokenStream {
	let type_params: Vec<&syn::Ident> =
		generics.type_params().map(|tp| &tp.ident).collect();
	if type_params.is_empty() {
		TokenStream::default()
	} else {
		quote! { ::<#(#type_params),*> }
	}
}


// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod test {
	use super::*;
	use alloc::string::String;
	use alloc::string::ToString;
	use quote::quote;

	fn parse_str(attr: TokenStream, item: syn::ItemFn) -> String {
		parse(attr, item).unwrap().to_string()
	}

	fn parse_err(attr: TokenStream, item: syn::ItemFn) -> String {
		parse(attr, item).unwrap_err().to_string()
	}

	// -----------------------------------------------------------------------
	// Action kind inference
	// -----------------------------------------------------------------------

	#[test]
	fn async_fn_uses_new_async() {
		let result = parse_str(
			quote!(),
			syn::parse_quote! { async fn my_action() -> i32 { 42 } },
		);
		assert!(result.contains("Action :: new_async"));
		assert!(result.contains("async fn my_action_action"));
	}

	#[test]
	fn pure_fn_uses_new_pure() {
		let result = parse_str(
			quote!(pure),
			syn::parse_quote! { fn my_action() -> i32 { 42 } },
		);
		assert!(result.contains("Action :: new_pure"));
		assert!(!result.contains("Action :: new_system"));
		assert!(!result.contains("Action :: new_async"));
	}

	#[test]
	fn plain_fn_uses_new_system() {
		let result = parse_str(
			quote!(),
			syn::parse_quote! { fn my_action(val: In<i32>) -> i32 { val.0 } },
		);
		assert!(result.contains("Action :: new_system"));
		assert!(!result.contains("Action :: new_pure"));
		assert!(!result.contains("Action :: new_async"));
	}

	// -----------------------------------------------------------------------
	// Multi-argument rejection
	// -----------------------------------------------------------------------

	#[test]
	fn multi_arg_async_errors() {
		let err = parse_err(
			quote!(),
			syn::parse_quote! { async fn bad(a: i32, b: i32) -> i32 { a + b } },
		);
		assert!(err.contains("at most one parameter"));
	}

	#[test]
	fn multi_arg_pure_errors() {
		let err = parse_err(
			quote!(pure),
			syn::parse_quote! { fn bad(a: i32, b: i32) -> i32 { a + b } },
		);
		assert!(err.contains("at most one parameter"));
	}

	// -----------------------------------------------------------------------
	// Pure (func) action tests
	// -----------------------------------------------------------------------

	#[test]
	fn pure_no_args_no_return() {
		let result =
			parse_str(quote!(pure), syn::parse_quote! { fn my_action() {} });
		assert!(result.contains("struct my_action"));
		assert!(result.contains("type In = ()"));
		assert!(result.contains("type Out = ()"));
		assert!(result.contains("let _ = __action_cx . input"));
		assert!(result.contains("Action :: new_pure"));
		assert!(result.contains("fn my_action_action"));
	}

	#[test]
	fn pure_single_arg() {
		let result = parse_str(
			quote!(pure),
			syn::parse_quote! { fn double(val: i32) -> i32 { val * 2 } },
		);
		assert!(result.contains("type In = i32"));
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("let val = __action_cx . input"));
		assert!(result.contains("Action :: new_pure"));
		assert!(result.contains("fn double_action"));
	}

	#[test]
	fn pure_tuple_destructure() {
		let result = parse_str(
			quote!(pure),
			syn::parse_quote! { fn add((a, b): (i32, i32)) -> i32 { a + b } },
		);
		assert!(result.contains("type In = (i32 , i32)"));
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("let (a , b) = __action_cx . input"));
		assert!(result.contains("Action :: new_pure"));
	}

	#[test]
	fn pure_result_return() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			fn fallible(val: i32) -> Result<i32> { Ok(val) }
		});
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("Action :: new_pure"));
	}

	#[test]
	fn pure_result_out_flag() {
		let result = parse_str(quote!(pure, result_out), syn::parse_quote! {
			fn fallible(val: i32) -> Result<i32> { Ok(val) }
		});
		assert!(result.contains("type Out = Result < i32 >"));
		assert!(result.contains("Action :: new_pure"));
	}

	#[test]
	fn pure_passthrough_action_context() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			fn my_action(cx: ActionContext<i32>) -> i32 { *cx }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_pure"));
		assert!(result.contains("fn my_action_action"));
		assert!(result.contains("cx : "));
		assert!(!result.contains("__action_cx"));
	}

	#[test]
	fn pure_passthrough_default_unit() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			fn my_action(cx: ActionContext) -> i32 { 1 }
		});
		assert!(result.contains("type In = ()"));
		assert!(result.contains("Action :: new_pure"));
		assert!(!result.contains("__action_cx"));
	}

	#[test]
	fn visibility_preserved() {
		let result = parse_str(
			quote!(pure),
			syn::parse_quote! { pub fn public_action() {} },
		);
		assert!(result.contains("pub struct public_action"));
	}

	// -----------------------------------------------------------------------
	// Async action tests
	// -----------------------------------------------------------------------

	#[test]
	fn async_no_args() {
		let result = parse_str(
			quote!(),
			syn::parse_quote! { async fn my_action() -> i32 { 42 } },
		);
		assert!(result.contains("struct my_action"));
		assert!(result.contains("type In = ()"));
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("Action :: new_async"));
		assert!(result.contains("async fn my_action_action"));
	}

	#[test]
	fn async_single_arg() {
		let result = parse_str(quote!(), syn::parse_quote! {
			async fn negate(val: i32) -> i32 { -val }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_async"));
		assert!(result.contains("let val = __action_cx . input"));
	}

	#[test]
	fn async_result_return() {
		let result = parse_str(quote!(), syn::parse_quote! {
			async fn fallible(val: i32) -> Result<i32> { Ok(val) }
		});
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("Action :: new_async"));
	}

	#[test]
	fn async_result_out() {
		let result = parse_str(quote!(result_out), syn::parse_quote! {
			async fn fallible(val: i32) -> Result<i32> { Ok(val) }
		});
		assert!(result.contains("type Out = Result < i32 >"));
		assert!(result.contains("Action :: new_async"));
	}

	// -----------------------------------------------------------------------
	// Async passthrough
	// -----------------------------------------------------------------------

	#[test]
	fn async_passthrough_action_context() {
		let result = parse_str(quote!(), syn::parse_quote! {
			async fn my_action(cx: ActionContext<i32>) -> i32 { *cx }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_async"));
		assert!(result.contains("async fn my_action_action"));
		assert!(!result.contains("__action_cx"));
	}

	#[test]
	fn async_passthrough_default_unit() {
		let result = parse_str(quote!(), syn::parse_quote! {
			async fn my_action(cx: ActionContext) -> i32 { 42 }
		});
		assert!(result.contains("type In = ()"));
		assert!(result.contains("Action :: new_async"));
		assert!(!result.contains("__action_cx"));
	}

	// -----------------------------------------------------------------------
	// System action tests
	// -----------------------------------------------------------------------

	#[test]
	fn system_basic() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(val: In<i32>) -> i32 { val.0 * 2 }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("ActionContext"));
		assert!(result.contains("let val = In (__action_cx . input)"));
	}

	#[test]
	fn system_with_system_params() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(val: In<i32>, time: Res<Time>) -> f32 { val.0 as f32 }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("time : Res < Time >"));
		assert!(result.contains("let val = In (__action_cx . input)"));
	}

	#[test]
	fn system_result() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(val: In<i32>) -> Result<i32> { Ok(val.0) }
		});
		assert!(result.contains("type Out = i32"));
		assert!(result.contains("Action :: new_system"));
	}

	#[test]
	fn system_unit_in_unit_out() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(val: In<()>) {}
		});
		assert!(result.contains("type In = ()"));
		assert!(result.contains("type Out = ()"));
		assert!(result.contains("Action :: new_system"));
	}

	#[test]
	fn system_no_input_all_system_params() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(commands: Commands) {}
		});
		assert!(result.contains("type In = ()"));
		assert!(result.contains("Action :: new_system"));
		// commands is a system param, not consumed as input
		assert!(result.contains("commands : Commands"));
		assert!(result.contains("let _ = __action_cx . input"));
	}

	// -----------------------------------------------------------------------
	// System passthrough
	// -----------------------------------------------------------------------

	#[test]
	fn system_passthrough_in_action_context() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(cx: In<ActionContext<i32>>) -> Entity { cx.id() }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("In (cx)"));
		assert!(!result.contains("__action_cx"));
	}

	#[test]
	fn system_passthrough_with_params() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(cx: In<ActionContext<i32>>, time: Res<Time>) -> f32 { 0.0 }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("time : Res < Time >"));
		assert!(result.contains("In (cx)"));
	}

	#[test]
	fn system_passthrough_default_unit() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(cx: In<ActionContext>) -> Entity { cx.id() }
		});
		assert!(result.contains("type In = ()"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("In (cx)"));
		assert!(!result.contains("__action_cx"));
	}

	#[test]
	fn system_passthrough_direct() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(cx: ActionContext<i32>) -> Entity { cx.id() }
		});
		assert!(result.contains("type In = i32"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("In (cx)"));
		assert!(!result.contains("__action_cx"));
	}

	#[test]
	fn system_passthrough_direct_default_unit() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(cx: ActionContext) -> Entity { cx.id() }
		});
		assert!(result.contains("type In = ()"));
		assert!(result.contains("Action :: new_system"));
		assert!(result.contains("In (cx)"));
		assert!(!result.contains("__action_cx"));
	}

	// -----------------------------------------------------------------------
	// Generics propagation
	// -----------------------------------------------------------------------

	#[test]
	fn async_passthrough_with_generics() {
		let result = parse_str(quote!(), syn::parse_quote! {
			async fn my_action<T>(input: ActionContext) -> ()
			where
				T: Send + Sync,
			{}
		});
		assert!(result.contains("struct my_action"));
		assert!(result.contains("PhantomData"));
		assert!(result.contains("where T : Send + Sync"));
		assert!(result.contains("impl < T >"));
		assert!(
			result
				.contains("IntoAction < my_action < T > > for my_action < T >")
		);
	}

	#[test]
	fn pure_action_with_generics() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			fn my_action<T>(val: i32) -> i32
			where
				T: Clone,
			{ val }
		});
		assert!(result.contains("PhantomData"));
		assert!(result.contains("where T : Clone"));
		assert!(result.contains("impl < T >"));
		assert!(
			result
				.contains("IntoAction < my_action < T > > for my_action < T >")
		);
		assert!(result.contains("Action :: new_pure"));
	}

	#[test]
	fn multi_generic_struct() {
		let result = parse_str(quote!(), syn::parse_quote! {
			async fn my_action<A, B>(input: ActionContext) -> ()
			where
				A: Send,
				B: Sync,
			{}
		});
		assert!(result.contains("PhantomData < (A , B) >"));
	}

	#[test]
	fn generic_with_reflect_uses_fn_phantom() {
		let result = parse_str(quote!(), syn::parse_quote! {
			#[derive(Component, Reflect)]
			#[reflect(Component)]
			async fn my_action<T>(input: ActionContext) -> ()
			where
				T: Send + Sync,
			{}
		});
		assert!(result.contains("reflect (ignore)"));
		assert!(result.contains("fn () ->"));
	}

	// -----------------------------------------------------------------------
	// has_derive helper
	// -----------------------------------------------------------------------

	#[test]
	fn detect_component_derive() {
		let item: syn::ItemFn = syn::parse_quote! {
			#[derive(Debug, Clone, Component, Reflect)]
			fn Add() {}
		};
		assert!(!item.attrs.is_empty());
		assert!(has_derive(&item.attrs, "Component"));
	}

	#[test]
	fn detect_no_component_derive() {
		let item: syn::ItemFn = syn::parse_quote! {
			#[derive(Debug, Clone)]
			fn Add() {}
		};
		assert!(!item.attrs.is_empty());
		assert!(!has_derive(&item.attrs, "Component"));
	}

	#[test]
	fn detect_no_derives_at_all() {
		let item: syn::ItemFn = syn::parse_quote! {
			fn Add() {}
		};
		assert!(item.attrs.is_empty());
		assert!(!has_derive(&item.attrs, "Component"));
	}

	// -----------------------------------------------------------------------
	// Component derive + #[require] generation
	// -----------------------------------------------------------------------

	#[test]
	fn component_derive_adds_require_pure() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			#[derive(Debug, Clone, Component, Reflect)]
			fn Add(val: i32) -> i32 { val }
		});
		assert!(
			result.contains("derive (Debug , Clone , Component , Reflect)")
		);
		assert!(result.contains("# [require"));
		assert!(result.contains("Action <"));
		assert!(result.contains("Action :: new_pure (add_action"));
		assert!(result.contains("struct Add"));
		assert!(result.contains("fn add_action"));
	}

	#[test]
	fn no_component_derive_no_require() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			#[derive(Debug, Clone)]
			fn my_action(val: i32) -> i32 { val }
		});
		assert!(result.contains("derive (Debug , Clone)"));
		assert!(!result.contains("# [require"));
		assert!(result.contains("fn my_action_action"));
	}

	#[test]
	fn no_derives_no_require() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			fn my_action(val: i32) -> i32 { val }
		});
		assert!(!result.contains("# [require"));
		assert!(result.contains("fn my_action_action"));
	}

	#[test]
	fn async_component_derive_adds_require() {
		let result = parse_str(quote!(), syn::parse_quote! {
			#[derive(Debug, Component, Reflect)]
			async fn HelpHandler(cx: ActionContext<Request>) -> Result<Outcome<Response, Request>> {
				todo!()
			}
		});
		assert!(result.contains("derive (Debug , Component , Reflect)"));
		assert!(result.contains("# [require"));
		assert!(result.contains("Action :: new_async (help_handler_action"));
		assert!(result.contains("struct HelpHandler"));
		assert!(result.contains("async fn help_handler_action"));
	}

	#[test]
	fn system_component_derive_adds_require() {
		let result = parse_str(quote!(), syn::parse_quote! {
			#[derive(Debug, Component, Reflect)]
			fn Increment(val: In<()>, query: Query<&Name>) -> Result<i64> {
				Ok(1)
			}
		});
		assert!(result.contains("derive (Debug , Component , Reflect)"));
		assert!(result.contains("# [require"));
		assert!(result.contains("Action :: new_system (increment_action"));
		assert!(result.contains("struct Increment"));
		assert!(result.contains("fn increment_action"));
	}

	// -----------------------------------------------------------------------
	// ActionMeta require
	// -----------------------------------------------------------------------

	#[test]
	fn component_reflect_adds_reflect_meta() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			#[derive(Component, Reflect)]
			fn Add(val: i32) -> i32 { val }
		});
		assert!(result.contains("ActionMeta"));
		assert!(result.contains("of_reflect :: < Self , _ > ()"));
	}

	#[test]
	fn component_without_reflect_adds_action_meta() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			#[derive(Component)]
			fn Add(val: i32) -> i32 { val }
		});
		assert!(result.contains("ActionMeta"));
		assert!(result.contains("of_action :: < Self , _ > ()"));
	}

	#[test]
	fn no_component_no_action_meta() {
		let result = parse_str(quote!(), syn::parse_quote! {
			fn my_action(val: In<i32>) -> i32 { val.0 }
		});
		assert!(!result.contains("of_action"));
		assert!(!result.contains("of_reflect"));
	}

	#[test]
	fn middleware_reflect_uses_handler_meta() {
		let result = parse_str(quote!(), syn::parse_quote! {
			#[derive(Default, Clone, Component, Reflect)]
			async fn HelpHandler(cx: ActionContext<(Request, Next<Request, Response>)>) -> Result<Response> {
				todo!()
			}
		});
		assert!(result.contains("ActionMeta"));
		assert!(result.contains("of_handler :: < Self , _ > ()"));
	}

	// -----------------------------------------------------------------------
	// route attribute
	// -----------------------------------------------------------------------

	#[test]
	fn route_bare_wraps_with_exchange_action() {
		let result = parse_str(quote!(route), syn::parse_quote! {
			#[derive(Component, Reflect)]
			async fn MyAction(val: i32) -> String { val.to_string() }
		});
		assert!(result.contains("ExchangeAction"));
		assert!(result.contains("new_detached"));
		assert!(result.contains("Action <"));
		assert!(!result.contains("PathPartial"));
	}

	#[test]
	fn route_with_path_adds_path_partial() {
		let result = parse_str(quote!(route = "home"), syn::parse_quote! {
			#[derive(Component, Reflect)]
			async fn MyAction(val: i32) -> String { val.to_string() }
		});
		assert!(result.contains("ExchangeAction"));
		assert!(result.contains("Action <"));
		assert!(result.contains("PathPartial"));
		assert!(result.contains("PathPartial :: new (\"home\")"));
	}

	#[test]
	fn route_with_expression_adds_path_partial() {
		let result =
			parse_str(quote!(route = get_route_path()), syn::parse_quote! {
				#[derive(Component, Reflect)]
				async fn MyAction(val: i32) -> String { val.to_string() }
			});
		assert!(result.contains("ExchangeAction"));
		assert!(result.contains("PathPartial"));
		assert!(result.contains("PathPartial :: new (get_route_path ())"));
	}

	#[test]
	fn route_without_component_no_path_partial() {
		let result = parse_str(quote!(route = "home"), syn::parse_quote! {
			async fn my_action(val: i32) -> String { val.to_string() }
		});
		assert!(!result.contains("PathPartial"));
		assert!(!result.contains("# [require"));
	}

	#[test]
	fn route_with_path_and_action_meta() {
		let result = parse_str(quote!(route = "validate"), syn::parse_quote! {
			#[derive(Component, Reflect)]
			async fn Validate(input: String) -> String { input }
		});
		assert!(result.contains("ExchangeAction"));
		assert!(result.contains("PathPartial :: new (\"validate\")"));
		assert!(result.contains("of_reflect :: < Self , _ > ()"));
	}

	// -----------------------------------------------------------------------
	// Doc and misc
	// -----------------------------------------------------------------------

	#[test]
	fn doc_attrs_forwarded() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			/// Does stuff.
			fn my_action(val: i32) -> i32 { val }
		});
		assert!(result.contains("doc"));
		assert!(result.contains("struct my_action"));
	}

	#[test]
	fn handler_at_module_level() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			fn add(val: i32) -> i32 { val }
		});
		// The handler function should be at module level so #[require] can reference it
		assert!(result.contains("fn into_action"));
		assert!(result.contains("Action :: new_pure (add_action)"));
		assert!(result.contains("fn add_action"));
	}

	#[test]
	fn generic_component_with_turbofish() {
		let result = parse_str(quote!(pure), syn::parse_quote! {
			#[derive(Debug, Component)]
			fn MyAction<T>(val: i32) -> i32
			where T: Clone,
			{ val }
		});
		assert!(result.contains("# [require"));
		assert!(
			result.contains("Action :: new_pure (my_action_action :: < T >")
		);
		assert!(result.contains("fn my_action_action < T >"));
	}
}
