[package]
name = "file_based_routes"
version.workspace = true
edition.workspace = true


[features]
config = ["beet/web-config"]
server = ["beet/web-server"]
client = ["beet/web-client"]


[dependencies]
serde.workspace = true
beet = { workspace = true }
