//! Versioned artifact storage for deploy, rollback, and rollforward.
use beet_core::prelude::*;
use beet_net::prelude::*;
use bytes::Bytes;

/// Metadata about a deployed version.
/// Generated by [`Stack::create_ledger`] for each deployment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ArtifactLedger {
	pub deploy_id: Uuid,
	pub timestamp: String,
	pub artifacts: HashMap<SmolStr, ArtifactEntry>,
}

impl ArtifactLedger {
	/// Create a new ledger with the given deploy id and timestamp.
	pub fn new(deploy_id: Uuid, timestamp: String) -> Self {
		Self {
			deploy_id,
			timestamp,
			artifacts: default(),
		}
	}

	/// Register an artifact in this ledger.
	/// Returns an error if an artifact with this label already exists.
	pub fn push_artifact(
		&mut self,
		label: impl Into<SmolStr>,
		entry: ArtifactEntry,
	) -> Result<()> {
		let label = label.into();
		if self.artifacts.contains_key(&label) {
			bevybail!(
				"artifact with label '{}' already exists in ledger {}",
				label,
				self.deploy_id
			);
		}
		self.artifacts.insert(label, entry);
		Ok(())
	}
}

/// Metadata about a single artifact within a version.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ArtifactEntry {
	/// S3 key where the artifact binary is stored
	pub bucket_key: SmolStr,
	/// Base64-encoded SHA256 hash for Terraform source_code_hash
	pub source_hash: SmolStr,
}

/// Runtime client for artifact operations on a provisioned bucket.
#[derive(Debug, Clone)]
pub struct ArtifactsClient {
	bucket: Bucket,
}

impl ArtifactsClient {
	pub fn new(bucket: Bucket) -> Self { Self { bucket } }

	/// Ensure the artifacts bucket exists, creating if needed.
	pub async fn ensure_bucket(&self) -> Result {
		self.bucket.bucket_try_create().await
	}

	/// Upload a single artifact binary to the versioned path.
	pub async fn upload_artifact(
		&self,
		uuid: &Uuid,
		artifact_name: &str,
		bytes: impl Into<Bytes>,
	) -> Result {
		let key = version_artifact_key(uuid, artifact_name);
		self.bucket.insert(&key, bytes).await
	}

	/// Upload the version ledger and set it as current.
	pub async fn publish_ledger(&self, ledger: &ArtifactLedger) -> Result {
		let bytes = serde_json::to_vec_pretty(ledger)?;
		// store version ledger
		self.bucket
			.insert(&version_ledger_key(&ledger.deploy_id), bytes.clone())
			.await?;
		// set as current
		self.bucket.insert(&current_ledger_key(), bytes).await
	}

	/// Read the current ledger.
	pub async fn current_ledger(&self) -> Result<Option<ArtifactLedger>> {
		let key = current_ledger_key();
		if !self.bucket.exists(&key).await? {
			return Ok(None);
		}
		let bytes = self.bucket.get(&key).await?;
		serde_json::from_slice(&bytes).map(Some).map_err(Into::into)
	}

	/// Download an artifact by name and version.
	pub async fn download(
		&self,
		artifact_name: &str,
		version: &Uuid,
	) -> Result<Bytes> {
		let key = version_artifact_key(version, artifact_name);
		self.bucket.get(&key).await
	}

	/// Set a specific version as the current version.
	pub async fn set_current(&self, version: &Uuid) -> Result {
		let ledger_bytes =
			self.bucket.get(&version_ledger_key(version)).await?;
		self.bucket
			.insert(&current_ledger_key(), ledger_bytes)
			.await
	}

	/// List all deployed versions, sorted chronologically.
	/// Only collects versioned ledger entries, excluding the current pointer.
	pub async fn list_versions(&self) -> Result<Vec<Uuid>> {
		let all_keys = self.bucket.list().await?;
		let mut versions: Vec<Uuid> = all_keys
			.iter()
			.filter_map(|key| {
				let key_str = key.to_string();
				// match exactly versions/{uuid}/ledger.json
				let parts: Vec<&str> = key_str.splitn(3, '/').collect();
				if parts.len() != 3
					|| parts[0] != "versions"
					|| parts[2] != "ledger.json"
				{
					return None;
				}
				Uuid::parse_str(parts[1]).ok()
			})
			.collect();
		versions.sort();
		Ok(versions)
	}

	/// Roll back N versions from the current version.
	pub async fn rollback(&self, count: usize) -> Result<Uuid> {
		let versions = self.list_versions().await?;
		let current = self
			.current_ledger()
			.await?
			.ok_or_else(|| bevyhow!("no current version to rollback from"))?;
		let current_idx = versions
			.iter()
			.position(|ver| *ver == current.deploy_id)
			.ok_or_else(|| {
				bevyhow!("current version not found in version list")
			})?;
		let target_idx = current_idx.checked_sub(count).ok_or_else(|| {
			bevyhow!(
				"cannot rollback {count} versions, only {current_idx} available"
			)
		})?;
		let target = versions[target_idx];
		self.set_current(&target).await?;
		Ok(target)
	}

	/// Roll forward to the latest version.
	pub async fn rollforward(&self) -> Result<Uuid> {
		let versions = self.list_versions().await?;
		let target = versions.last().ok_or_else(|| {
			bevyhow!("no versions available to rollforward to")
		})?;
		self.set_current(target).await?;
		Ok(*target)
	}
}

fn current_ledger_key() -> RelPath { RelPath::new("current-ledger.json") }

fn version_ledger_key(uuid: &Uuid) -> RelPath {
	RelPath::new(format!("versions/{uuid}/ledger.json"))
}
fn version_artifact_key(uuid: &Uuid, artifact_name: &str) -> RelPath {
	RelPath::new(format!("versions/{uuid}/{artifact_name}"))
}

pub(crate) fn now_timestamp() -> String {
	let duration = SystemTime::now()
		.duration_since(SystemTime::UNIX_EPOCH)
		.unwrap_or_default();
	format!("{}s", duration.as_secs())
}


#[cfg(test)]
mod tests {
	use super::*;

	fn test_ledger(artifacts: Vec<(&str, &str, &str)>) -> ArtifactLedger {
		let mut ledger = ArtifactLedger::new(Uuid::now_v7(), now_timestamp());
		for (name, artifact_key, hash) in artifacts {
			ledger
				.push_artifact(name, ArtifactEntry {
					bucket_key: artifact_key.into(),
					source_hash: hash.into(),
				})
				.unwrap();
		}
		ledger
	}

	#[beet_core::test]
	async fn upload_and_download() {
		let client = ArtifactsClient::new(temp_bucket());
		let uuid = Uuid::now_v7();
		let bytes = b"hello world".to_vec();
		client
			.upload_artifact(&uuid, "my-app.zip", bytes.clone())
			.await
			.unwrap();
		let downloaded = client.download("my-app.zip", &uuid).await.unwrap();
		downloaded.to_vec().xpect_eq(bytes);
	}

	#[beet_core::test]
	async fn publish_and_read_ledger() {
		let client = ArtifactsClient::new(temp_bucket());
		client.current_ledger().await.unwrap().xpect_eq(None);
		let ledger =
			test_ledger(vec![("app.zip", "versions/x/app.zip", "abc123")]);
		client.publish_ledger(&ledger).await.unwrap();
		let current = client.current_ledger().await.unwrap().unwrap();
		current.deploy_id.xpect_eq(ledger.deploy_id);
		current.artifacts.len().xpect_eq(1);
	}

	#[beet_core::test]
	async fn list_versions_sorted() {
		let client = ArtifactsClient::new(temp_bucket());
		let ledger1 = test_ledger(vec![("app.zip", "v1", "h1")]);
		let ledger2 = test_ledger(vec![("app.zip", "v2", "h2")]);
		client.publish_ledger(&ledger1).await.unwrap();
		client.publish_ledger(&ledger2).await.unwrap();
		let versions = client.list_versions().await.unwrap();
		versions.xpect_eq(vec![ledger1.deploy_id, ledger2.deploy_id]);
	}

	#[beet_core::test]
	async fn rollback_and_rollforward() {
		let client = ArtifactsClient::new(temp_bucket());
		let ledger1 = test_ledger(vec![("app.zip", "v1", "h1")]);
		let ledger2 = test_ledger(vec![("app.zip", "v2", "h2")]);
		let ledger3 = test_ledger(vec![("app.zip", "v3", "h3")]);
		client.publish_ledger(&ledger1).await.unwrap();
		client.publish_ledger(&ledger2).await.unwrap();
		client.publish_ledger(&ledger3).await.unwrap();
		// rollback from latest
		let rolled = client.rollback(1).await.unwrap();
		rolled.xpect_eq(ledger2.deploy_id);
		let rolled = client.rollback(1).await.unwrap();
		rolled.xpect_eq(ledger1.deploy_id);
		// rollforward to latest
		let forwarded = client.rollforward().await.unwrap();
		forwarded.xpect_eq(ledger3.deploy_id);
	}

	#[beet_core::test]
	async fn rollback_too_far_fails() {
		let client = ArtifactsClient::new(temp_bucket());
		let ledger = test_ledger(vec![("app.zip", "v1", "h1")]);
		client.publish_ledger(&ledger).await.unwrap();
		client.rollback(1).await.unwrap_err();
	}
}
