use crate::style::TokenMap;
use crate::style::colors;
use crate::style::tones;
use beet_core::prelude::*;

pub fn light() -> TokenMap<Color> {
	TokenMap::default()
		.with(colors::PRIMARY, tones::PRIMARY_40)
		.with(colors::ON_PRIMARY, tones::PRIMARY_100)
		.with(colors::PRIMARY_CONTAINER, tones::PRIMARY_90)
		.with(colors::ON_PRIMARY_CONTAINER, tones::PRIMARY_10)
		.with(colors::SECONDARY, tones::SECONDARY_40)
		.with(colors::ON_SECONDARY, tones::SECONDARY_100)
		.with(colors::SECONDARY_CONTAINER, tones::SECONDARY_90)
		.with(colors::ON_SECONDARY_CONTAINER, tones::SECONDARY_10)
		.with(colors::TERTIARY, tones::TERTIARY_40)
		.with(colors::ON_TERTIARY, tones::TERTIARY_100)
		.with(colors::TERTIARY_CONTAINER, tones::TERTIARY_90)
		.with(colors::ON_TERTIARY_CONTAINER, tones::TERTIARY_10)
		.with(colors::ERROR, tones::ERROR_40)
		.with(colors::ON_ERROR, tones::ERROR_100)
		.with(colors::ERROR_CONTAINER, tones::ERROR_90)
		.with(colors::ON_ERROR_CONTAINER, tones::ERROR_10)
		.with(colors::BACKGROUND, tones::NEUTRAL_99)
		.with(colors::ON_BACKGROUND, tones::NEUTRAL_10)
		.with(colors::SURFACE, tones::NEUTRAL_99)
		.with(colors::ON_SURFACE, tones::NEUTRAL_10)
		.with(colors::SURFACE_VARIANT, tones::NEUTRAL_VARIANT_90)
		.with(colors::ON_SURFACE_VARIANT, tones::NEUTRAL_VARIANT_30)
		.with(colors::OUTLINE, tones::NEUTRAL_VARIANT_50)
		.with(colors::OUTLINE_VARIANT, tones::NEUTRAL_VARIANT_80)
		.with(colors::SHADOW, tones::NEUTRAL_0)
		.with(colors::SCRIM, tones::NEUTRAL_0)
		.with(colors::INVERSE_SURFACE, tones::NEUTRAL_20)
		.with(colors::INVERSE_ON_SURFACE, tones::NEUTRAL_95)
		.with(colors::INVERSE_PRIMARY, tones::PRIMARY_80)
}

pub fn dark() -> TokenMap<Color> {
	TokenMap::default()
		.with(colors::PRIMARY, tones::PRIMARY_80)
		.with(colors::ON_PRIMARY, tones::PRIMARY_20)
		.with(colors::PRIMARY_CONTAINER, tones::PRIMARY_30)
		.with(colors::ON_PRIMARY_CONTAINER, tones::PRIMARY_90)
		.with(colors::SECONDARY, tones::SECONDARY_80)
		.with(colors::ON_SECONDARY, tones::SECONDARY_20)
		.with(colors::SECONDARY_CONTAINER, tones::SECONDARY_30)
		.with(colors::ON_SECONDARY_CONTAINER, tones::SECONDARY_90)
		.with(colors::TERTIARY, tones::TERTIARY_80)
		.with(colors::ON_TERTIARY, tones::TERTIARY_20)
		.with(colors::TERTIARY_CONTAINER, tones::TERTIARY_30)
		.with(colors::ON_TERTIARY_CONTAINER, tones::TERTIARY_90)
		.with(colors::ERROR, tones::ERROR_80)
		.with(colors::ON_ERROR, tones::ERROR_20)
		.with(colors::ERROR_CONTAINER, tones::ERROR_30)
		.with(colors::ON_ERROR_CONTAINER, tones::ERROR_80)
		.with(colors::BACKGROUND, tones::NEUTRAL_10)
		.with(colors::ON_BACKGROUND, tones::NEUTRAL_90)
		.with(colors::SURFACE, tones::NEUTRAL_10)
		.with(colors::ON_SURFACE, tones::NEUTRAL_90)
		.with(colors::SURFACE_VARIANT, tones::NEUTRAL_VARIANT_30)
		.with(colors::ON_SURFACE_VARIANT, tones::NEUTRAL_VARIANT_80)
		.with(colors::OUTLINE, tones::NEUTRAL_VARIANT_60)
		.with(colors::OUTLINE_VARIANT, tones::NEUTRAL_VARIANT_30)
		.with(colors::SHADOW, tones::NEUTRAL_0)
		.with(colors::SCRIM, tones::NEUTRAL_0)
		.with(colors::INVERSE_SURFACE, tones::NEUTRAL_90)
		.with(colors::INVERSE_ON_SURFACE, tones::NEUTRAL_20)
		.with(colors::INVERSE_PRIMARY, tones::PRIMARY_40)
}
