//! The sovereign DKIM key: one signing pair this stack owns, per mail domain.
use crate::prelude::*;
use beet_action::prelude::*;
use beet_core::prelude::*;
use beet_net::prelude::*;

/// `<EnsureDkimKey/>` — mint the signing key each mail domain publishes its own
/// `stalwart` selector for, park the private half in parameter store, and hand
/// the public half to the apply as the variable that selector's `TXT` record
/// reads.
///
/// Outbound mail is signed twice from here on: SES Easy DKIM signs with a key
/// Amazon holds and rotates, and Stalwart signs with this one. Two signatures
/// are not redundancy for its own sake — a receiver needs only one to pass, so
/// the pair is what makes the relay replaceable. Nothing about the domain's
/// deliverability then depends on a key somebody else can revoke.
///
/// Create-IF-MISSING, exactly like [`EnsureSecret`], and for a sharper reason:
/// a rotated key whose record has not propagated is a fortnight of mail signed
/// by a selector the world cannot resolve. Rotation is a second selector added
/// beside this one, never a value overwritten in place.
///
/// The pair is generated by `openssl` and the private half never touches the
/// deploy machine's disk: it is written to the tool's stdin and read back from
/// its stdout. Nothing here logs either half.
///
/// This step is why the `deploy` route is the interface and a bare `apply` is
/// not: a tofu variable nobody supplied defaults to empty, and an empty `p=` is
/// the wire form of a REVOKED selector rather than of a missing one.
#[derive(Debug, Clone, Get, SetWith, Component, Reflect)]
#[reflect(Component, Default)]
#[require(EnsureDkimKeyAction)]
pub struct EnsureDkimKey {
	/// Modulus size. RSA-2048 is the DKIM interoperability floor and ceiling at
	/// once: 1024 is deprecated and 4096 does not fit one `TXT` string, which
	/// some resolvers still handle badly.
	bits: u32,
}

impl Default for EnsureDkimKey {
	fn default() -> Self { Self { bits: Self::BITS } }
}

impl EnsureDkimKey {
	/// See [`bits`](Self::bits).
	pub const BITS: u32 = 2048;

	/// The `p=` half of a selector record: the base64 `SubjectPublicKeyInfo`
	/// carried by the PEM, ie its armour and its line breaks removed.
	///
	/// A DKIM record's key is exactly that encoding, so this is a de-armouring
	/// rather than a conversion, and it is the one step between what `openssl`
	/// prints and what a verifier reads.
	pub fn public_key_from_pem(pem: &str) -> Result<String> {
		let key = pem
			.lines()
			.filter(|line| !line.starts_with("-----"))
			.collect::<String>()
			.xmap(|key| key.trim().to_string());
		match key.is_empty() {
			true => bevybail!("openssl printed no public key"),
			false => key.xok(),
		}
	}

	/// A fresh private key, as PKCS#8 PEM (what Stalwart's `DkimSignature`
	/// stores and what `openssl pkey` reads back).
	async fn generate(&self) -> Result<String> {
		ChildProcess::new("openssl")
			.with_not_found(Self::OPENSSL_NOT_FOUND)
			.with_args([
				"genpkey".to_string(),
				"-algorithm".to_string(),
				"RSA".to_string(),
				"-pkeyopt".to_string(),
				format!("rsa_keygen_bits:{}", self.bits),
			])
			.run_async_stdout()
			.await
	}

	/// The public half of `private_pem`, as
	/// [`public_key_from_pem`](Self::public_key_from_pem) wants it.
	async fn public_key(private_pem: &str) -> Result<String> {
		ChildProcess::new("openssl")
			.with_not_found(Self::OPENSSL_NOT_FOUND)
			.with_args(["pkey", "-pubout"])
			.with_secret(private_pem)
			.run_async_stdin(private_pem)
			.await?
			.stdout
			.xmap(|stdout| String::from_utf8_lossy(&stdout).to_string())
			.xmap(|pem| Self::public_key_from_pem(&pem))
	}

	const OPENSSL_NOT_FOUND: &'static str = "openssl is not installed, and the sovereign DKIM key is generated with it";
}

/// Mints whatever is missing and passes every domain's public key on to the
/// apply as a `-var`.
#[action(handler_only)]
#[derive(Default, Component, Reflect)]
#[reflect(Component, Default)]
pub async fn EnsureDkimKeyAction(
	cx: ActionContext<Request>,
) -> Result<Outcome<Request, Response>> {
	let ensure = cx
		.caller
		.get_cloned::<EnsureDkimKey>()
		.await
		.unwrap_or_default();
	let mail = cx
		.caller
		.with_state::<MailQuery, _>(|entity, query| query.resolve(entity))
		.await??;
	let region = mail.stack.region().clone();

	let mut input = cx.input;
	// only the domains whose records this stack publishes: a domain somebody
	// else holds the zone for would get a key no record ever points at.
	for domain in mail
		.domains
		.iter()
		.filter(|domain| domain.records().proves_identity())
	{
		let name = domain.dkim_secret().name(&mail.stack);
		let private = match ssm_ext::get(&region, &name).await? {
			Some(private) => private,
			None => {
				let generated = ensure.generate().await?;
				match ssm_ext::create(&region, &name, &generated).await {
					Ok(()) => {
						info!("minted the {} signing key", domain.domain());
						generated
					}
					// the loser of a race re-reads rather than overwriting: two
					// deploys must not disagree about which key is published.
					Err(err) if ssm_ext::is_already_exists(&err) => {
						ssm_ext::get(&region, &name).await?.ok_or_else(
							|| {
								bevyhow!(
									"dkim key {name} vanished between writes"
								)
							},
						)?
					}
					Err(err) => return Err(err),
				}
			}
		};
		input = input.with_param(
			domain.dkim_public_key_variable().key(),
			&EnsureDkimKey::public_key(&private).await?,
		);
	}
	Pass(input).xok()
}

#[cfg(test)]
mod tests {
	use super::*;

	/// The record's `p=` is the PEM's payload and nothing else: armour or a
	/// stray newline inside the value makes a key no verifier can parse, and
	/// the failure surfaces as `dkim=permerror` on somebody else's server.
	#[beet_core::test]
	fn the_public_key_is_the_pem_payload() {
		EnsureDkimKey::public_key_from_pem(
			"-----BEGIN PUBLIC KEY-----\nMIIBIjAN\nAQEFAAOC\n-----END PUBLIC KEY-----\n",
		)
		.unwrap()
		.as_str()
		.xpect_eq("MIIBIjANAQEFAAOC");
	}

	/// An empty answer is an error rather than an empty record: `p=` with no
	/// key is the wire form of a REVOKED selector, so publishing one would
	/// silently withdraw the signature instead of failing the deploy.
	#[beet_core::test]
	fn an_empty_key_is_never_published() {
		EnsureDkimKey::public_key_from_pem("")
			.unwrap_err()
			.to_string()
			.xpect_contains("no public key");
	}
}
