//! The other half of MTA-STS: the policy a sender actually fetches.
use crate::prelude::*;
use beet_action::prelude::*;
use beet_core::prelude::*;
use beet_net::prelude::*;
use serde_json::json;
use std::collections::BTreeMap;

/// `<MtaStsPublish/>` — serve every mail domain's MTA-STS policy at the
/// well-known url a sending server looks for it, as one Cloudflare Worker.
///
/// The `_mta-sts` TXT record and the policy body are two halves of one
/// statement: the record says a policy exists and carries an id, and the policy
/// says what it is. Terraform publishes the record; nothing published the body
/// until this, so senders found the record, failed to fetch a policy and cached
/// none — which withholds no mail from a `testing` policy but also protects
/// none.
///
/// A Worker rather than the mail box itself, for two reasons that are really
/// one: `0.16` does not serve the well-known path at all, and a policy served
/// by the box it authorises is a policy that goes away exactly when it matters.
/// The edge serves it from a host with its own certificate, provisioned by the
/// same upload as a wrangler *custom domain*, which is why this record is the
/// one in the zone terraform does not own and the zone audit allows.
///
/// The bodies ride the Worker's own configuration rather than a bucket beside
/// it: a policy is a hundred bytes and its whole content is generated from the
/// declarations already in the stack, so a store in between would be one more
/// thing to be stale.
#[derive(Debug, Clone, Get, SetWith, Component, Reflect)]
#[reflect(Component, Default)]
#[require(MtaStsPublishAction)]
pub struct MtaStsPublish {
	/// The Worker's name, which is also its `target/<name>-cf` project
	/// directory. Stack-composed by the action when left empty, so the usual
	/// declaration names nothing at all.
	worker: SmolStr,
}

impl Default for MtaStsPublish {
	fn default() -> Self {
		Self {
			worker: SmolStr::default(),
		}
	}
}

impl MtaStsPublish {
	/// The wrangler `var` the policy bodies arrive in, keyed by the host each
	/// is served at.
	pub const POLICIES_VAR: &'static str = "MTA_STS_POLICIES";

	/// The label the worker's name composes from when none is declared.
	pub const LABEL: &'static str = "mta-sts";

	/// The Worker script: one route, one lookup, and a `404` for anything else.
	///
	/// Every host it serves shares this script, so the policy is chosen by the
	/// `Host` the request arrived on. That is what makes a second mail domain a
	/// second entry in a map rather than a second Worker.
	pub fn script() -> String {
		format!(
			r#"// Serves each mail domain's MTA-STS policy at the well-known path.
// The bodies are generated by the beet mail stack; edit the declaration, not this.
const PATH = "/{path}";

export default {{
	async fetch(request, env) {{
		const url = new URL(request.url);
		if (url.pathname !== PATH) {{
			return new Response("not found\n", {{ status: 404 }});
		}}
		const policies = JSON.parse(env.{var} || "{{}}");
		const policy = policies[url.hostname];
		if (policy === undefined) {{
			return new Response("no policy for this host\n", {{ status: 404 }});
		}}
		return new Response(policy, {{
			status: 200,
			headers: {{
				"content-type": "text/plain; charset=utf-8",
				"cache-control": "no-cache",
			}},
		}});
	}},
}};
"#,
			path = MtaStsPolicy::WELL_KNOWN_PATH,
			var = Self::POLICIES_VAR
		)
	}

	/// The `wrangler.jsonc` for `policies`, whose keys are both the hosts the
	/// Worker answers on and the map it looks a body up in.
	///
	/// Each host is a *custom domain*, so wrangler creates its zone record and
	/// its certificate: an MTA-STS policy fetched over anything less than a
	/// valid https connection is ignored by the sender, which would make a
	/// half-configured host indistinguishable from no policy at all.
	pub fn wrangler_json(
		worker: &str,
		policies: &BTreeMap<String, String>,
	) -> Result<String> {
		json!({
			"name": worker,
			"main": "worker.js",
			"compatibility_date": wrangler_ext::COMPATIBILITY_DATE,
			"routes": policies
				.keys()
				.map(|host| json!({ "pattern": host, "custom_domain": true }))
				.collect::<Vec<_>>(),
			"vars": {
				Self::POLICIES_VAR: serde_json::to_string(policies)?,
			},
		})
		.xmap(|config| serde_json::to_string_pretty(&config))?
		.xok()
	}
}

/// Writes the project and uploads it, one Worker for every domain the stack
/// serves mail for.
#[action(handler_only)]
#[derive(Default, Component, Reflect)]
#[reflect(Component, Default)]
pub async fn MtaStsPublishAction(
	cx: ActionContext<Request>,
) -> Result<Outcome<Request, Response>> {
	let publish = cx
		.caller
		.get_cloned::<MtaStsPublish>()
		.await
		.unwrap_or_default();
	let mail = cx.caller.with_world(MailStack::resolve).await??;

	// only the domains this stack publishes an `_mta-sts` record for: a policy
	// served for a host with no record is a policy nothing looks for, and a
	// record with no policy is the state this action exists to end.
	let policies = mail
		.domains
		.iter()
		.filter(|domain| domain.records().serves_mail())
		.map(|domain| {
			(
				MtaStsPolicy::host(domain.domain()),
				domain.mta_sts_policy_text(),
			)
		})
		.collect::<BTreeMap<_, _>>();
	if policies.is_empty() {
		info!("no domain under this stack publishes an mta-sts policy");
		return Pass(cx.input).xok();
	}

	let worker = match publish.worker().is_empty() {
		true => mail.stack.resource_name(MtaStsPublish::LABEL),
		false => publish.worker().to_string(),
	};
	let dir = wrangler_ext::project_dir(&worker)?;
	fs_ext::write_async(dir.join("worker.js"), MtaStsPublish::script()).await?;
	fs_ext::write_async(
		dir.join("wrangler.jsonc"),
		MtaStsPublish::wrangler_json(&worker, &policies)?,
	)
	.await?;
	wrangler_ext::deploy(&dir, None).await?;

	for host in policies.keys() {
		info!(
			"policy served at https://{host}/{}",
			MtaStsPolicy::WELL_KNOWN_PATH
		);
	}
	Pass(cx.input).xok()
}

#[cfg(test)]
mod tests {
	use super::*;

	fn policies() -> BTreeMap<String, String> {
		[
			(
				"mta-sts.stalwart.beetmash.com".to_string(),
				MtaStsPolicy::default().policy_text(&["mail.beetmash.com"]),
			),
			(
				"mta-sts.news.beetmash.com".to_string(),
				MtaStsPolicy::default().policy_text(&["mail.beetmash.com"]),
			),
		]
		.into_iter()
		.collect()
	}

	/// Every host is a custom domain, since wrangler provisions the record AND
	/// the certificate with the upload: a policy fetched over anything less
	/// than valid https is discarded by the sender, silently.
	#[beet_core::test]
	fn every_host_is_a_custom_domain() {
		MtaStsPublish::wrangler_json("beetmash--prod--mta-sts", &policies())
			.unwrap()
			.as_str()
			.xpect_contains("\"pattern\": \"mta-sts.news.beetmash.com\"")
			.xpect_contains("\"pattern\": \"mta-sts.stalwart.beetmash.com\"")
			.xpect_contains("\"custom_domain\": true");
	}

	/// The bodies ride as one json var the script parses, so a second domain is
	/// an entry rather than a Worker. The policy text is the wire format, CRLF
	/// included, so it is asserted as escaped json rather than as prose.
	#[beet_core::test]
	fn the_policies_ride_as_one_var() {
		MtaStsPublish::wrangler_json("mta-sts", &policies())
			.unwrap()
			.as_str()
			.xpect_contains("MTA_STS_POLICIES")
			.xpect_contains("version: STSv1\\\\r\\\\nmode: testing");
	}

	/// The path is the rfc's and nothing else: a sender fetches exactly it, so
	/// the script and [`MtaStsPolicy`] must not be able to disagree.
	#[beet_core::test]
	fn the_script_serves_the_well_known_path() {
		MtaStsPublish::script()
			.as_str()
			.xpect_contains("\"/.well-known/mta-sts.txt\"");
	}
}
