//! The other half of MTA-STS: the host that serves the policy a sender actually
//! fetches, and both halves of its lifecycle.
use crate::prelude::*;
use beet_action::prelude::*;
use beet_core::prelude::*;
use beet_net::prelude::*;
use serde_json::json;
use std::collections::BTreeMap;




/// `<MtaStsPolicyHost up={$attach_up} down={$attach_down}/>` — the Cloudflare
/// Worker serving every mail domain's MTA-STS policy, declared as a thing the
/// stack HAS rather than as a step some verb does.
///
/// One tag, one file position, two actions: the publish joins the deploy group
/// and the removal joins the teardown group, so both groups' member lists are
/// projections of the same insert order and cannot drift apart.
///
/// Named for the host rather than the policy because [`MtaStsPolicy`] is the
/// policy: a value composed from each domain's declaration. This is the thing
/// that serves it.
///
/// It is a declaration rather than a resource because wrangler owns it, not
/// terraform: the script, its bindings and its custom domains are one upload,
/// and the certificate for a custom domain is issued by that upload. Without the
/// down half the Worker survives every destroy, and the next deploy cannot
/// attach the same hostnames to a second one.
#[template]
pub fn MtaStsPolicyHost(
	/// The group the publish joins, ie the stack's post-apply attach group.
	#[prop(required)]
	up: Entity,
	/// The group the removal joins, ie the stack's teardown attach group.
	#[prop(required)]
	down: Entity,
) -> impl Bundle {
	children![
		(MtaStsPublish::default(), MemberOf(up)),
		(MtaStsUnpublish::default(), MemberOf(down)),
	]
}

impl MtaStsPublish {
	/// The wrangler `var` the policy bodies arrive in, keyed by the host each
	/// is served at.
	pub const POLICIES_VAR: &'static str = "MTA_STS_POLICIES";

	/// The label the worker's name composes from when none is declared.
	pub const LABEL: &'static str = "mta-sts";

	/// The Worker script: one route, one lookup, and a `404` for anything else.
	///
	/// Every host it serves shares this script, so the policy is chosen by the
	/// `Host` the request arrived on. That is what makes a second mail domain a
	/// second entry in a map rather than a second Worker.
	pub fn script() -> String {
		format!(
			r#"// Serves each mail domain's MTA-STS policy at the well-known path.
// The bodies are generated by the beet mail stack; edit the declaration, not this.
const PATH = "/{path}";

export default {{
	async fetch(request, env) {{
		const url = new URL(request.url);
		if (url.pathname !== PATH) {{
			return new Response("not found\n", {{ status: 404 }});
		}}
		const policies = JSON.parse(env.{var} || "{{}}");
		const policy = policies[url.hostname];
		if (policy === undefined) {{
			return new Response("no policy for this host\n", {{ status: 404 }});
		}}
		return new Response(policy, {{
			status: 200,
			headers: {{
				"content-type": "text/plain; charset=utf-8",
				"cache-control": "no-cache",
			}},
		}});
	}},
}};
"#,
			path = MtaStsPolicy::WELL_KNOWN_PATH,
			var = Self::POLICIES_VAR
		)
	}

	/// The `wrangler.jsonc` for `policies`, whose keys are both the hosts the
	/// Worker answers on and the map it looks a body up in.
	///
	/// Each host is a *custom domain*, so wrangler creates its zone record and
	/// its certificate: an MTA-STS policy fetched over anything less than a
	/// valid https connection is ignored by the sender, which would make a
	/// half-configured host indistinguishable from no policy at all.
	pub fn wrangler_json(
		worker: &str,
		policies: &BTreeMap<String, String>,
	) -> Result<String> {
		json!({
			"name": worker,
			"main": "worker.js",
			"compatibility_date": wrangler_ext::COMPATIBILITY_DATE,
			"routes": policies
				.keys()
				.map(|host| json!({ "pattern": host, "custom_domain": true }))
				.collect::<Vec<_>>(),
			"vars": {
				Self::POLICIES_VAR: serde_json::to_string(policies)?,
			},
		})
		.xmap(|config| serde_json::to_string_pretty(&config))?
		.xok()
	}
}

/// Writes the project and uploads it, one Worker for every domain the stack
/// serves mail for.
/// `<MtaStsPublish/>` — serve every mail domain's MTA-STS policy at the
/// well-known url a sending server looks for it, as one Cloudflare Worker.
///
/// The `_mta-sts` TXT record and the policy body are two halves of one
/// statement: the record says a policy exists and carries an id, and the policy
/// says what it is. Terraform publishes the record; nothing published the body
/// until this, so senders found the record, failed to fetch a policy and cached
/// none — which withholds no mail from a `testing` policy but also protects
/// none.
///
/// A Worker rather than the mail box itself, for two reasons that are really
/// one: `0.16` does not serve the well-known path at all, and a policy served
/// by the box it authorises is a policy that goes away exactly when it matters.
/// The edge serves it from a host with its own certificate, provisioned by the
/// same upload as a wrangler *custom domain*, which is why this record is the
/// one in the zone terraform does not own and the zone audit allows.
///
/// The bodies ride the Worker's own configuration rather than a bucket beside
/// it: a policy is a hundred bytes and its whole content is generated from the
/// declarations already in the stack, so a store in between would be one more
/// thing to be stale.
#[action]
#[derive(Component, Reflect)]
#[reflect(Component, Default)]
pub async fn MtaStsPublish(
	/// The Worker's name, which is also its `target/<name>-cf` project
	/// directory. Stack-composed by the action when left empty, so the usual
	/// declaration names nothing at all.
	#[field(default = SmolStr::default())]
	worker: SmolStr,
	cx: ActionContext<Request>,
) -> Result<Outcome<Request, Response>> {
	let mail = cx.caller.with_world(MailStack::resolve).await??;

	// only the domains this stack publishes an `_mta-sts` record for: a policy
	// served for a host with no record is a policy nothing looks for, and a
	// record with no policy is the state this action exists to end.
	let policies = mail
		.domains
		.iter()
		.filter(|domain| domain.records().serves_mail())
		.map(|domain| {
			(
				MtaStsPolicy::host(domain.domain()),
				domain.mta_sts_policy_text(),
			)
		})
		.collect::<BTreeMap<_, _>>();
	if policies.is_empty() {
		info!("no domain under this stack publishes an mta-sts policy");
		return Pass(cx.input).xok();
	}

	let worker = match worker.is_empty() {
		true => mail.stack.resource_name(MtaStsPublish::LABEL),
		false => worker.to_string(),
	};
	let dir = wrangler_ext::project_dir(&worker)?;
	fs_ext::write_async(dir.join("worker.js"), MtaStsPublish::script()).await?;
	fs_ext::write_async(
		dir.join("wrangler.jsonc"),
		MtaStsPublish::wrangler_json(&worker, &policies)?,
	)
	.await?;
	wrangler_ext::deploy(&dir, None).await?;

	for host in policies.keys() {
		info!(
			"policy served at https://{host}/{}",
			MtaStsPolicy::WELL_KNOWN_PATH
		);
	}
	Pass(cx.input).xok()
}

/// Removes every custom domain the policy is served at, then the Worker itself.
/// `<MtaStsUnpublish/>` — the teardown half of [`MtaStsPolicyHost`].
///
/// It runs BEFORE `tofu destroy`, because the Worker converges after the apply
/// that published the `_mta-sts` records it answers for, and teardown order is
/// convergence order reversed. That ordering matters in the other direction
/// too: a hostname cannot be attached to two Workers, so a Worker that survives
/// a destroy blocks the next deploy of the same stack, which is exactly what
/// happened before this existed.
///
/// The custom domains come off one at a time and the script comes off last,
/// because the script is per-STACK (`<app>--<stage>--mta-sts`) while the custom
/// domains are per-domain: removing it on the first domain would strip the
/// policy from every domain still served by it. Deleting a custom domain takes
/// its zone record and its certificate with it, since the upload created all
/// three together.
///
/// A no-op when neither exists: a teardown walks declarations rather than a
/// ledger of what was created, so every down-action has to succeed against a
/// resource that was never there.
#[action]
#[derive(Component, Reflect)]
#[reflect(Component, Default)]
pub async fn MtaStsUnpublish(
	/// The Worker's name, stack-composed when left empty exactly as
	/// [`MtaStsPublish`] composes it.
	#[field(default = SmolStr::default())]
	worker: SmolStr,
	cx: ActionContext<Request>,
) -> Result<Outcome<Request, Response>> {
	let mail = cx.caller.with_world(MailStack::resolve).await??;
	let worker = match worker.is_empty() {
		true => mail.stack.resource_name(MtaStsPublish::LABEL),
		false => worker.to_string(),
	};
	let hosts = mail
		.domains
		.iter()
		.filter(|domain| domain.records().serves_mail())
		.map(|domain| MtaStsPolicy::host(domain.domain()))
		.collect::<Vec<_>>();

	for removal in MtaStsUnpublish::removals(&hosts, &worker) {
		match &removal {
			MtaStsRemoval::CustomDomain(host) => {
				match wrangler_ext::delete_custom_domain(host).await? {
					true => info!("removed the custom domain at {host}"),
					false => info!("no custom domain at {host}"),
				}
			}
			MtaStsRemoval::Script(name) => {
				match wrangler_ext::delete_script(name).await? {
					true => info!("removed the mta-sts worker `{name}`"),
					false => info!("no mta-sts worker `{name}`"),
				}
			}
		}
	}
	Pass(cx.input).xok()
}

impl MtaStsUnpublish {
	/// What a teardown removes, in order.
	///
	/// Split out because the ORDER is the load-bearing part and nothing about a
	/// live api call says so: every host's custom domain first, the shared script
	/// last.
	fn removals(hosts: &[String], worker: &str) -> Vec<MtaStsRemoval> {
		hosts
			.iter()
			.cloned()
			.map(MtaStsRemoval::CustomDomain)
			.chain([MtaStsRemoval::Script(worker.to_string())])
			.collect()
	}
}

/// One thing an [`MtaStsUnpublish`] removes.
#[derive(Debug, PartialEq, Eq)]
enum MtaStsRemoval {
	/// A per-domain custom domain, with its record and its certificate.
	CustomDomain(String),
	/// The per-stack Worker script every custom domain pointed at.
	Script(String),
}

#[cfg(test)]
mod tests {
	use super::*;

	fn policies() -> BTreeMap<String, String> {
		[
			(
				"mta-sts.stalwart.beetmash.com".to_string(),
				MtaStsPolicy::default().policy_text(&["mail.beetmash.com"]),
			),
			(
				"mta-sts.news.beetmash.com".to_string(),
				MtaStsPolicy::default().policy_text(&["mail.beetmash.com"]),
			),
		]
		.into_iter()
		.collect()
	}

	/// Every host is a custom domain, since wrangler provisions the record AND
	/// the certificate with the upload: a policy fetched over anything less
	/// than valid https is discarded by the sender, silently.
	#[beet_core::test]
	fn every_host_is_a_custom_domain() {
		MtaStsPublish::wrangler_json("beetmash--prod--mta-sts", &policies())
			.unwrap()
			.as_str()
			.xpect_contains("\"pattern\": \"mta-sts.news.beetmash.com\"")
			.xpect_contains("\"pattern\": \"mta-sts.stalwart.beetmash.com\"")
			.xpect_contains("\"custom_domain\": true");
	}

	/// The bodies ride as one json var the script parses, so a second domain is
	/// an entry rather than a Worker. The policy text is the wire format, CRLF
	/// included, so it is asserted as escaped json rather than as prose.
	#[beet_core::test]
	fn the_policies_ride_as_one_var() {
		MtaStsPublish::wrangler_json("mta-sts", &policies())
			.unwrap()
			.as_str()
			.xpect_contains("MTA_STS_POLICIES")
			.xpect_contains("version: STSv1\\\\r\\\\nmode: testing");
	}

	/// The script is per-stack and the custom domains are per-domain, so the
	/// removal takes every domain off first and the script last: taking it off
	/// with the first domain would strip the policy from every domain still
	/// served by it.
	#[beet_core::test]
	fn the_last_domain_takes_the_script() {
		let hosts = policies().keys().cloned().collect::<Vec<_>>();
		MtaStsUnpublish::removals(&hosts, "beetmash--prod--mta-sts").xpect_eq(
			vec![
				MtaStsRemoval::CustomDomain(hosts[0].clone()),
				MtaStsRemoval::CustomDomain(hosts[1].clone()),
				MtaStsRemoval::Script("beetmash--prod--mta-sts".to_string()),
			],
		);
	}

	/// A stack whose domains publish no policy still had a worker, and a
	/// teardown that walks the declaration removes it: the drill case, where a
	/// down-action has to succeed against a resource that may never have
	/// existed.
	#[beet_core::test]
	fn a_stack_with_no_policies_still_removes_its_worker() {
		MtaStsUnpublish::removals(&[], "beetmash--drill--mta-sts").xpect_eq(
			vec![MtaStsRemoval::Script(
				"beetmash--drill--mta-sts".to_string(),
			)],
		);
	}

	/// The path is the rfc's and nothing else: a sender fetches exactly it, so
	/// the script and [`MtaStsPolicy`] must not be able to disagree.
	#[beet_core::test]
	fn the_script_serves_the_well_known_path() {
		MtaStsPublish::script()
			.as_str()
			.xpect_contains("\"/.well-known/mta-sts.txt\"");
	}
}
