



/// A technique for applying html partials to rsx nodes.
/// The partials are generated by the beet cli without the need
/// for recompilation, which allows for hot reloading.
pub struct ReverseRsx;


// impl ReverseRsx{
