



/// Reverse Rsx, aka reverse templating is a technique for applying html partials to rsx nodes.
/// The partials are generated by the beet cli via static analasis
///  which allows for hot reloading without recompilation.
pub struct ReverseRsx;


// impl ReverseRsx{
