use crate::prelude::*;
use beet_core::prelude::*;

pub type UserId = Uuid7<User>;

#[derive(
	Debug,
	Clone,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
	Component,
)]
pub struct User {
	id: UserId,
	/// The name of the user used when building context
	name: String,
	kind: UserKind,
}

impl Document for User {
	type Id = UserId;
	fn id(&self) -> Self::Id { self.id }
}

impl User {
	pub fn new(name: impl AsRef<str>, kind: UserKind) -> Self {
		Self {
			id: default(),
			name: name.as_ref().to_string(),
			kind,
		}
	}
	pub fn system() -> Self { Self::new("System", UserKind::System) }
	pub fn developer() -> Self { Self::new("Developer", UserKind::Developer) }
	pub fn human() -> Self { Self::new("Human", UserKind::Human) }
	pub fn agent() -> Self { Self::new("Agent", UserKind::Agent) }

	pub fn name(&self) -> &str { &self.name }
	pub fn kind(&self) -> UserKind { self.kind }
}

/// The kind of user this entity is.
/// Distinct from [`OpenResponses::MessageRole`] in that
/// [`UserKind`] is absolute, whereas the difference between
/// `MessageRole::User` and `MessageRole::Asssistant` is relative
/// to the agent
#[derive(
	Debug,
	Clone,
	Copy,
	PartialEq,
	Eq,
	PartialOrd,
	Ord,
	Hash,
	Serialize,
	Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum UserKind {
	/// Messages generated by this user will always be treated as [`MessageRole::System`]
	System,
	/// Messages generated by this user will always be treated as [`MessageRole::Developer`]
	Developer,
	/// Messages generated by this user will always be treated as [`MessageRole::User`]
	Human,
	/// Messages generated by this user may be treated as [`MessageRole::Assistant`] or [`MessageRole::User`],
	/// depending on the originator of the message.
	Agent,
}

impl std::fmt::Display for UserKind {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			UserKind::System => write!(f, "system"),
			UserKind::Developer => write!(f, "developer"),
			UserKind::Human => write!(f, "human"),
			UserKind::Agent => write!(f, "agent"),
		}
	}
}


impl UserKind {
	pub fn input_str(&self) -> &'static str {
		match self {
			UserKind::System => "system",
			UserKind::Developer => "developer",
			UserKind::Human => "human",
			UserKind::Agent => "agent",
		}
	}
}
