[package]
name = "beet_template_macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
# css = ["beet_parse/css"]
# bevy = []

[lib]
proc-macro = true

[dependencies]
beet_common = { workspace = true, features = ["tokens"] }
beet_parse.workspace = true
sweet = { workspace = true, features = ["bevy"] }
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
proc-macro2-diagnostics.workspace = true
anyhow.workspace = true

[dev-dependencies]
sweet = { workspace = true, features = ["test", "bevy"] }
