[build]
# recommended for cargo test --workspace
# jobs = 8

[target.wasm32-unknown-unknown]
# this uses sweet for cargo run and cargo test
runner = 'sweet test-wasm'
rustflags = [
	"--cfg",
	"getrandom_backend=\"wasm_js\"",
]

[env]
SWEET_ROOT = { value = "", relative = true }