
run:
  just watch 'just build'

vite *args:
  npx vite --port=3006 {{args}}

build:
	npx vite build
# cp -r ./dist/* ./public

deploy:
	just build
	firebase deploy --only hosting:beet-mash-demo

publish:
	npm version patch
	just build
	npm publish

preview:
	npx vite preview

watch *command:
	forky watch \
	-w '**/*.ts' \
	-w '**/*.tsx' \
	-w '**/*.css' \
	-i '{.git,dist}/**' \
	-- {{command}}

serve:
	cd dist && forky serve --port=3007 --any-origin