
run:
  just watch 'just build'

# run:
#   npx vite

build:
	npx vite build
	cp -r ./dist/* ./public

publish:
	npm version patch
	just build
	npm publish

preview:
	npx vite preview

watch *command:
	forky watch \
	-w '**/*.ts' \
	-w '**/*.tsx' \
	-w '**/*.css' \
	-i '{.git,dist}/**' \
	-- {{command}}

serve:
	cd public && forky serve --port=3007 --any-origin