[package]
name = "beet-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description = "CLI for beet authoring tools"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "beet"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
beet = { workspace = true, features = ["router", "build"] }
# beet_router = { workspace = true, features = ["parser"] }
anyhow.workspace = true
ron.workspace = true
sweet = { workspace = true, features = ["fs", "server"] }
clap.workspace = true
tokio.workspace = true
rapidhash.workspace = true


[dev-dependencies]
sweet = { workspace = true, features = ["test"] }
