[package]
name = "beet_rsx"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true


[features]
default = ["macros", "fs", "serde", "html"]
# TODO deprecate
css = ["beet_rsx_macros?/css"]
reactive_graph = ["dep:reactive_graph", "dep:any_spawner"]
html = ["dep:html-escape"]
macros = ["dep:beet_rsx_macros"]
parser = ["dep:quote", "dep:proc-macro2"]
fs = ["sweet/fs"]
serde = ["beet_common/serde", "dep:serde", "dep:ron"]
bevy = ["dep:bevy", "serde", "dep:flume"]
bevy_default = ["bevy", "bevy/default"]
e2e = ["sweet/e2e"]

[dependencies]
# beet_rsx_parser = { workspace = true, optional = true }
beet_rsx_macros = { workspace = true, optional = true }
beet_common.workspace = true
sweet.workspace = true

#💡 utils
anyhow.workspace = true
thiserror.workspace = true
extend.workspace = true
strum.workspace = true
rapidhash.workspace = true
strum_macros.workspace = true
prettyplease.workspace = true
once_cell.workspace = true
http.workspace = true

#💡 html
html-escape = { version = "0.2", optional = true }

#💡 serde
serde = { workspace = true, optional = true }
ron = { workspace = true, optional = true }

#💡 parser
quote = { workspace = true, optional = true }
proc-macro2 = { workspace = true, optional = true }

#💡 reactivity
reactive_graph = { version = "0.2.0-rc3", optional = true, features = [
	"nightly",
	"effects",
] }
any_spawner = { version = "0", optional = true, features = [
	"futures-executor",
	"wasm-bindgen",
	"tokio",
] }

#💡 bevy
bevy = { workspace = true, optional = true }
flume = { workspace = true, optional = true }

#💡 native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sweet = { workspace = true, features = ["fs"] }
tokio.workspace = true


#💡 wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
sweet = { workspace = true, features = ["web"] }
console_log.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true


[dev-dependencies]
beet_rsx = { path = "", features = ["parser", "bevy"] }
sweet = { workspace = true, features = ["test"] }
