[package]
name = "demo_site"
edition = "2024"

[features]
default = ["server"]
launch = ["beet/launch"]
server = ["beet/server"]
client = ["beet/client"]


[dependencies]
serde = "1"
beet = { path = "../../" }
