[package]
name = "demo_site"
version.workspace = true
edition.workspace = true


[features]
default = ["server"]
launch = ["beet/launch"]
server = ["beet/server"]
client = ["beet/client"]


[dependencies]
serde.workspace = true
beet = { workspace = true }

