[package]
name = "beet_build"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = ["markdown", "style"]
markdown = ["dep:pulldown-cmark"]
style = ["dep:lightningcss", "dep:parcel_selectors"]

[dependencies]
#💡 Internal
beet_rsx = { workspace = true, features = ["bevy"] }
beet_common.workspace = true
beet_router.workspace = true
beet_rsx_parser.workspace = true
sweet.workspace = true

#💡 Utils
thiserror.workspace = true
anyhow.workspace = true
rapidhash.workspace = true
futures.workspace = true
heck.workspace = true
rayon.workspace = true

#💡 Tokens
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
proc-macro2-diagnostics.workspace = true

#💡 Serde
serde.workspace = true
toml.workspace = true
ron.workspace = true
serde_json.workspace = true

#💡 Parsing
prettyplease.workspace = true
pulldown-cmark = { version = "0.13", optional = true }
# TODO direct dep, not workspace. this should be the only place
# we dep on lightning
clap.workspace = true

#💡 style
parcel_selectors = { workspace = true, optional = true }
lightningcss = { workspace = true, optional = true }

#💡 Bevy
bevy = { workspace = true }
flume = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true

[dev-dependencies]
sweet = { workspace = true, features = ["test", "bevy"] }
beet_router = { workspace = true, features = ["_test_site"] }
