//! The behaviour-tree leaf: a script run for what it does to the world.
use crate::prelude::*;
use beet_core::prelude::*;
use core::marker::PhantomData;
use serde::Serialize;
use serde::de::DeserializeOwned;

/// Reflectable marker making a sibling [`Script`] a behaviour-tree leaf.
///
/// Installs the typed [`ScriptAction`], a default [`ScriptConfig`], and the
/// `() -> Outcome` [`ActionOverload`] a tree calls the leaf through: the script
/// runs on its default input, whatever it returned is discarded, and the leaf
/// answers [`Outcome::PASS`]. What a world-capable script *did* is already in
/// the world; a route (`ExchangeScript`) is the front-end that answers with what
/// it returned.
///
/// A component rather than a template because [`ActionOverload`] is not
/// [`Reflect`]: it has to be regenerated by a reflectable owner's `#[require]`
/// when a scene reloads. [`RunScript`] is the markup front-end that spawns the
/// pair.
///
/// A leaf, so `<Repeat>` over it is a ticking dynamic system and `<Sequence>`
/// places it in a larger behaviour.
#[derive(Component, Reflect)]
#[reflect(Component, Default)]
// `Input` and `Output` only appear in the ignored phantom marker, so an empty
// `#[reflect(where)]` drops the default bound, as on [`Script`] itself.
#[reflect(where)]
#[require(
	ScriptAction<Input, Output>,
	ScriptConfig,
	ActionOverload<(), Outcome> = outcome_overload::<Input, Output>(),
)]
pub struct OutcomeScript<Input = Value, Output = Value>
where
	Input: 'static + Send + Sync + Default + Serialize,
	Output: 'static + Send + Sync + DeserializeOwned,
{
	#[reflect(ignore)]
	_marker: PhantomData<fn() -> (Input, Output)>,
}

/// A markup-friendly scripted leaf: a `script` acting on the world through the
/// promise-shaped `world` API.
///
/// ```bsx
/// <RunScript script="
///   const [entry] = await world.entities('bevy_ecs::name::Name');
///   const name = await world.get(entry, 'bevy_ecs::name::Name');
///   const copy = await world.spawn({ 'bevy_ecs::name::Name': name + ' (copy)' });
///   await world.insert(copy, 'guestbook.Visits', 1);
/// "/>
/// ```
///
/// Every `world` method is served against the live world the moment it is
/// awaited: a read returns current state, a write lands immediately and in
/// order, a `spawn` resolves to a real entity id usable by the next line, and a
/// refused call rejects the promise where it was made, catchable in the script.
///
/// What the script is granted rides alongside as a [`ScriptConfig`] spread, so a
/// narrower leaf is composition rather than a second tag:
/// `<RunScript {ScriptConfig{read:["Name"]}} script=".."/>`, or
/// `{ScriptConfig{world:false}}` for a provably pure one.
#[template]
pub fn RunScript(
	/// The JavaScript source, an async function body evaluated with the `world`
	/// API installed.
	#[prop(into)]
	script: String,
) -> impl Bundle {
	(
		Script::<Value, Value>::new(script),
		OutcomeScript::<Value, Value>::default(),
	)
}

/// The `() -> Outcome` overload a behaviour tree calls a scripted leaf through.
///
/// Delegates to the entity's canonical [`ScriptAction`] directly rather than
/// re-entering resolution, so it can never recurse. `Sequence` and friends call
/// their children as `(), Outcome`, which is why this pair is the one a tree
/// needs.
fn outcome_overload<Input, Output>() -> ActionOverload<(), Outcome>
where
	Input: 'static + Send + Sync + Default + Serialize,
	Output: 'static + Send + Sync + DeserializeOwned,
{
	ActionOverload::new(Action::new_async_local(
		async |cx: ActionContext<()>| -> Result<Outcome> {
			let action = cx
				.caller
				.get(|action: &Action<Input, Output>| action.clone())
				.await?;
			// the leaf hands the script its default input (`Value::Null` for the
			// untyped default) and discards what it answered with.
			cx.caller
				.call_detached(action, Input::default())
				.await
				.map(|_| Outcome::PASS)
		},
	))
}

// Manual impls avoid spurious bounds on the phantom marker's types, as on
// [`Script`].
impl<Input, Output> Default for OutcomeScript<Input, Output>
where
	Input: 'static + Send + Sync + Default + Serialize,
	Output: 'static + Send + Sync + DeserializeOwned,
{
	fn default() -> Self {
		Self {
			_marker: PhantomData,
		}
	}
}

impl<Input, Output> Clone for OutcomeScript<Input, Output>
where
	Input: 'static + Send + Sync + Default + Serialize,
	Output: 'static + Send + Sync + DeserializeOwned,
{
	fn clone(&self) -> Self { Self::default() }
}

impl<Input, Output> core::fmt::Debug for OutcomeScript<Input, Output>
where
	Input: 'static + Send + Sync + Default + Serialize,
	Output: 'static + Send + Sync + DeserializeOwned,
{
	fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
		f.debug_struct("OutcomeScript").finish()
	}
}

#[cfg(test)]
mod test {
	use crate::prelude::*;
	use crate::scripting::test_support::*;
	use beet_core::prelude::*;

	#[beet_core::test]
	async fn spawns_through_the_world_api() {
		let mut world = test_world();
		run_leaf(&mut world, r#"await world.spawn({ "Name": "ada" })"#)
			.await
			.unwrap()
			.xpect_eq(Outcome::PASS);
		world
			.query::<&Name>()
			.iter(&world)
			.next()
			.unwrap()
			.as_str()
			.xpect_eq("ada");
	}

	/// The markup front-end builds the same leaf: `<RunScript>` expands to the
	/// `(Script, OutcomeScript)` pair, so a spawned template ticks.
	#[beet_core::test]
	async fn the_template_builds_a_leaf() {
		let mut world = test_world();
		let leaf = world
			.spawn_template(rsx! {
				<RunScript script={r#"await world.spawn({ "Name": "ada" });"#}/>
			})
			.unwrap()
			.id();
		world
			.entity_mut(leaf)
			.call::<(), Outcome>(())
			.await
			.unwrap()
			.xpect_eq(Outcome::PASS);
		world.query::<&Name>().iter(&world).count().xpect_eq(1);
	}

	/// The capability the whole bridge is for: the read after the write sees the
	/// write, because both were served against the live world.
	#[beet_core::test]
	async fn a_script_reads_its_own_write() {
		let mut world = test_world();
		run_leaf(
			&mut world,
			r#"
			const entry = await world.spawn({ "Name": "ada" });
			const name = await world.get(entry, "Name");
			await world.insert(entry, "Name", name + " lovelace");
			"#,
		)
		.await
		.unwrap();
		world
			.query::<&Name>()
			.iter(&world)
			.next()
			.unwrap()
			.as_str()
			.xpect_eq("ada lovelace");
	}

	#[beet_core::test]
	async fn lists_the_entities_carrying_a_component() {
		let mut world = test_world();
		world.spawn(Name::new("ada"));
		world.spawn(Name::new("bob"));
		run_leaf(
			&mut world,
			r#"
			const found = await world.entities("bevy_ecs::name::Name");
			await world.spawn({ "Name": "count:" + found.length });
			"#,
		)
		.await
		.unwrap();
		world
			.query::<&Name>()
			.iter(&world)
			.any(|name| name.as_str() == "count:2")
			.xpect_true();
	}

	#[beet_core::test]
	async fn writes_land_in_evaluation_order() {
		let mut world = test_world();
		run_leaf(
			&mut world,
			r#"
			const entry = await world.spawn({});
			await world.insert(entry, "Name", "one");
			await world.insert(entry, "Name", "two");
			"#,
		)
		.await
		.unwrap();
		world
			.query::<&Name>()
			.iter(&world)
			.next()
			.unwrap()
			.as_str()
			.xpect_eq("two");
	}

	#[beet_core::test]
	async fn removes_and_despawns() {
		let mut world = test_world();
		let kept = world.spawn(Name::new("ada")).id();
		world.spawn(Name::new("bob"));
		run_leaf(
			&mut world,
			r#"
			for (const id of await world.entities("Name")) {
				if ((await world.get(id, "Name")) === "ada") {
					await world.remove(id, "Name");
				} else {
					await world.despawn(id);
				}
			}
			"#,
		)
		.await
		.unwrap();
		world.entity(kept).contains::<Name>().xpect_false();
		world.query::<&Name>().iter(&world).count().xpect_eq(0);
	}

	/// A refused write rejects the promise at the call site, so the script can
	/// catch it and carry on. That is what makes the grant a boundary the
	/// script can reason about rather than a trapdoor.
	#[beet_core::test]
	async fn a_refused_write_is_catchable_in_the_script() {
		let mut world = test_world();
		DynamicComponents::register(
			&mut world,
			"game.Refused",
			ValueSchema::Any,
		)
		.unwrap();
		let entity = world.spawn(Name::new("ada")).id();
		run_leaf_with(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			try {
				await world.insert(entry, "Name", "bob");
			} catch (err) {
				await world.insert(entry, "game.Refused", err.message);
			}
			"#,
			// everything but the name, so the catch block can still record what
			// it was refused
			ScriptConfig {
				write: GlobFilter::default().with_exclude("*Name"),
				..default()
			},
		)
		.await
		.unwrap()
		.xpect_eq(Outcome::PASS);
		world
			.entity(entity)
			.get::<Name>()
			.unwrap()
			.as_str()
			.xpect_eq("ada");
		read_value(&mut world, entity, "game.Refused")
			.to_string()
			.xpect_contains("may not write");
	}

	/// A script cannot widen its own reach, whatever its config says: the
	/// carrier components are refused by rule, which covers the toggles and the
	/// limits along with the filters.
	#[beet_core::test]
	async fn a_script_cannot_rewrite_its_own_config() {
		let mut world = test_world();
		world
			.resource::<AppTypeRegistry>()
			.write()
			.register::<ScriptConfig>();
		run_leaf(
			&mut world,
			r#"
			const entry = await world.spawn({});
			await world.insert(entry, "ScriptConfig", {});
			"#,
		)
		.await
		.unwrap_err()
		.to_string()
		.xpect_contains("no script may write");
	}

	/// A world with `game.Note` to record in and one named entity to work on.
	fn world_with(declarations: [(&str, ValueSchema); 1]) -> (World, Entity) {
		let mut world = test_world();
		for (name, schema) in declarations {
			DynamicComponents::register(&mut world, name, schema).unwrap();
		}
		DynamicComponents::register(&mut world, "game.Note", ValueSchema::Any)
			.unwrap();
		let entity = world.spawn(Name::new("ada")).id();
		(world, entity)
	}

	/// A declared schema is a contract the bridge enforces, and a rejection is
	/// the same catchable error a refusal is: the script sees one shape for
	/// "the host said no".
	#[beet_core::test]
	async fn a_declared_schema_rejects_a_non_conforming_value() {
		let (mut world, entity) =
			world_with([("game.Health", ValueSchema::U64(default()))]);
		run_leaf(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			await world.insert(entry, "game.Health", 3);
			try {
				await world.insert(entry, "game.Health", "three");
			} catch (err) {
				await world.insert(entry, "game.Note", err.message);
			}
			"#,
		)
		.await
		.unwrap();
		// the rejected value never reached the component's storage
		read_value(&mut world, entity, "game.Health").xpect_eq(Value::Uint(3));
		read_value(&mut world, entity, "game.Note")
			.to_string()
			.xpect_contains("`game.Health` does not accept this value");
	}

	/// The default is genuinely inert: an undeclared component takes whatever a
	/// document field can hold, exactly as it did before schemas existed.
	#[beet_core::test]
	async fn an_any_schema_accepts_everything() {
		let (mut world, entity) = world_with([("game.Loot", ValueSchema::Any)]);
		run_leaf(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			for (const value of [1, "sword", [1, 2], { held: true }, null]) {
				await world.insert(entry, "game.Loot", value);
			}
			"#,
		)
		.await
		.unwrap();
		read_value(&mut world, entity, "game.Loot").xpect_eq(Value::Null);
	}

	/// A schema the world has to resolve before it can decide, which is the
	/// case the async executor exists for: the operation reads the declaration
	/// under one exclusive section, lets go, and only then validates.
	#[beet_core::test]
	async fn validates_against_a_schema_the_world_resolved() {
		let (mut world, entity) = world_with([(
			"game.Health",
			ValueSchema::Reference("game.HealthValue".into()),
		)]);
		let mut registry = SchemaRegistry::default();
		registry.insert("game.HealthValue", ValueSchema::U64(default()));
		world.insert_resource(registry);
		run_leaf(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			await world.insert(entry, "game.Health", 3);
			try {
				await world.insert(entry, "game.Health", "three");
			} catch (err) {
				await world.insert(entry, "game.Note", err.message);
			}
			"#,
		)
		.await
		.unwrap();
		read_value(&mut world, entity, "game.Health").xpect_eq(Value::Uint(3));
		read_value(&mut world, entity, "game.Note")
			.to_string()
			.xpect_contains("does not accept this value");
	}

	/// `world.schema` answers a runtime component with its declaration, which
	/// is the contract every write to it is checked against.
	#[beet_core::test]
	async fn reads_the_declared_schema() {
		let (mut world, entity) =
			world_with([("game.Health", ValueSchema::U64(default()))]);
		run_leaf(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			const schema = await world.schema("game.Health");
			await world.insert(entry, "game.Note", JSON.stringify(schema));
			"#,
		)
		.await
		.unwrap();
		read_value(&mut world, entity, "game.Note")
			.to_string()
			.xpect_contains("game.Health")
			.xpect_contains("U64");
	}

	/// JavaScript has one number type and [`Value`] has three, so what a script
	/// reads back must be what it wrote. Pinned before any numeric schema can
	/// act on the distinction.
	#[beet_core::test]
	async fn round_trips_numbers_through_a_script() {
		let (mut world, entity) =
			world_with([("game.Number", ValueSchema::Any)]);
		run_leaf(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			const sent = [0, -1, 1.5, 9007199254740992];
			const seen = [];
			for (const value of sent) {
				await world.insert(entry, "game.Number", value);
				seen.push(await world.get(entry, "game.Number"));
			}
			await world.insert(entry, "game.Note", { sent, seen });
			"#,
		)
		.await
		.unwrap();
		let note = read_value(&mut world, entity, "game.Note");
		let note = note.as_map().unwrap();
		note.get("seen")
			.unwrap()
			.xpect_eq(note.get("sent").unwrap().clone())
			.as_list()
			.unwrap()
			.xpect_eq(vec![
				Value::Uint(0),
				Value::Int(-1),
				Value::Float(1.5),
				Value::Uint(9007199254740992),
			]);
	}

	/// A script can hold bytes. JSON has no byte type, so they cross the wire
	/// as a list of numbers and the *destination* restores the type: a
	/// [`Bytes`](ValueSchema::Bytes) schema coerces what arrives, so bytes read
	/// back and written again land as the identical bytes.
	#[beet_core::test]
	async fn round_trips_bytes_through_a_script() {
		let (mut world, entity) =
			world_with([("game.Blob", ValueSchema::Bytes(default()))]);
		run_leaf(
			&mut world,
			r#"
			const [entry] = await world.entities("Name");
			await world.insert(entry, "game.Blob", [1, 2, 3, 255]);
			const read = await world.get(entry, "game.Blob");
			await world.insert(entry, "game.Blob", read);
			await world.insert(entry, "game.Note", read);
			"#,
		)
		.await
		.unwrap();
		read_value(&mut world, entity, "game.Blob")
			.xpect_eq(Value::Bytes(vec![1, 2, 3, 255]));
		// what the script saw is the number list json can carry, which is what
		// makes the destination-directed coercion necessary
		read_value(&mut world, entity, "game.Note").xpect_eq(Value::List(
			vec![
				Value::Uint(1),
				Value::Uint(2),
				Value::Uint(3),
				Value::Uint(255),
			],
		));
	}

	/// A withheld global is absent rather than inert: `world: false` is what
	/// makes a script provably pure, on any backend.
	#[beet_core::test]
	async fn a_worldless_script_has_no_world_global() {
		run_script_with::<(), String>(
			"return typeof world",
			(),
			ScriptConfig::default().without_world(),
		)
		.await
		.unwrap()
		.xpect_eq("undefined".to_string());
	}

	/// Its sibling toggle, so the two grants are independently withheld.
	#[beet_core::test]
	async fn a_consoleless_script_has_no_console_global() {
		run_script_with::<(), String>(
			"return typeof console",
			(),
			ScriptConfig::default().without_console(),
		)
		.await
		.unwrap()
		.xpect_eq("undefined".to_string());
	}

	/// A bridged script answers like any other: the world changes what a script
	/// may do, not how it hands back a typed value.
	#[beet_core::test]
	async fn a_bridged_script_answers_a_typed_output() {
		let mut world = test_world();
		world.spawn(Name::new("ada"));
		world
			.spawn((
				Script::<(), String>::new(
					r#"
					const [entry] = await world.entities("Name");
					return "found " + (await world.get(entry, "Name"));
					"#,
				),
				ScriptAction::<(), String>::default(),
			))
			.call::<(), String>(())
			.await
			.unwrap()
			.xpect_eq("found ada".to_string());
	}

	/// The bridge is served inside one sync point, not one call per frame.
	///
	/// [`AsyncPlugin`]'s `max_async_ticks_per_sync_point` drives up to 100
	/// request/wake/poll rounds per sync point, and a bridged call is one
	/// round, so a script making a dozen of them settles inside a single
	/// update. Without that a `<Repeat>` over a `<RunScript>` would silently
	/// become one world call per frame.
	///
	/// Embedded engine only: an out-of-process backend is bounded by its
	/// transport (a process spawn, a `postMessage` round trip), not by the tick
	/// budget, so the question this pins does not arise there.
	///
	/// Both the driver and the script action are local tasks, so they share the
	/// world thread. A task on the shared pool belongs to a worker thread under
	/// `bevy_multithreaded`, which a sync point can only wake and hope for, and
	/// the dozen calls dribble out roughly one per frame.
	#[cfg(feature = "quickjs")]
	#[beet_core::test]
	async fn a_dozen_calls_settle_in_one_update() {
		let mut world = test_world();
		let script = (0..12)
			.map(|index| {
				format!(r#"await world.spawn({{"Name":"n{index}"}});"#)
			})
			.collect::<Vec<_>>()
			.join("\n");
		let entity = world
			.spawn((
				Script::<Value, Value>::new(script),
				OutcomeScript::<Value, Value>::default(),
			))
			.id();
		let (send, recv) = OnceValue::oneshot();
		world
			.entity_mut(entity)
			.run_async_local(move |entity| async move {
				send.signal(entity.call::<(), Outcome>(()).await);
			});
		let mut settled = Box::pin(recv.wait());
		let mut updates = 0;
		let outcome = loop {
			world.update_local();
			updates += 1;
			if let Some(outcome) =
				futures_lite::future::poll_once(&mut settled).await
			{
				break Some(outcome);
			}
			if updates == 10 {
				break None;
			}
		};
		outcome.unwrap().unwrap().xpect_eq(Outcome::PASS);
		updates.xpect_eq(1);
		world.query::<&Name>().iter(&world).count().xpect_eq(12);
	}

	/// The console still works alongside the bridge: installing one channel must
	/// not displace the other.
	#[beet_core::test]
	async fn the_console_survives_the_bridge() {
		let mut world = test_world();
		run_leaf(
			&mut world,
			r#"
			console.log("working");
			await world.spawn({ "Name": "ada" });
			"#,
		)
		.await
		.unwrap();
		world.query::<&Name>().iter(&world).count().xpect_eq(1);
	}
}
