[package]
name = "sweet_bevy"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
readme.workspace = true
description = "Bevy utilities"
repository.workspace = true

[features]
bevy_default = ["bevy/default"]
rand = ["dep:rand", "dep:rand_chacha", "dep:getrandom"]

[dependencies]
sweet_utils = { workspace = true, features = ["bevy"] }
bevy.workspace = true

anyhow.workspace = true
extend.workspace = true
rand = { workspace = true, optional = true }
rand_chacha = { workspace = true, optional = true }
getrandom = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
sweet_web.workspace = true
js-sys.workspace = true
# wasm-bindgen = { workspace = true, optional = true }
# wasm-bindgen-futures = { workspace = true, optional = true }
# web-sys = { workspace = true, optional = true }


[dev-dependencies]
sweet_test = { workspace = true, features = ["bevy"] }
sweet_bevy = { path = "", features = ["rand"] }
